/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_Libro_Contable;


import ModeloDAO.LibroDiarioDao;
import java.sql.SQLException;

/**
 *
 * @author Adrian
 */
public class frm_libroDiario extends javax.swing.JFrame {

    /**
     * Creates new form frm_libroDiario
     */
    public frm_libroDiario() throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle("Libro Diario");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        Ll.MostrarListaLibroContable();
       
        
      
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLibroDiario = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btbVolveMenu = new javax.swing.JButton();
        btbVerAsientoContable = new javax.swing.JButton();
        btbFiltrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestión de Inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Libro Diario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, 20));

        TablaLibroDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaLibroDiario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 1240, 360));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Desde :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));
        jPanel1.add(jDateDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 170, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hasta :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));
        jPanel1.add(jDateHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 170, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Filtrado Por Fecha");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, -1, -1));

        btbVolveMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolveMenu.setText("Volver");
        btbVolveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVolveMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btbVolveMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 664, 150, 40));

        btbVerAsientoContable.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVerAsientoContable.setText("Ver Asientos");
        btbVerAsientoContable.setToolTipText("");
        btbVerAsientoContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVerAsientoContableActionPerformed(evt);
            }
        });
        jPanel1.add(btbVerAsientoContable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        btbFiltrar.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btbFiltrar.setText("Filtrar");
        btbFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btbFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 680, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/FondoCompleto.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1370, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbVolveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVolveMenuActionPerformed
    
    }//GEN-LAST:event_btbVolveMenuActionPerformed

    private void btbVerAsientoContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVerAsientoContableActionPerformed

     

        // TODO add your handling code here:
    }//GEN-LAST:event_btbVerAsientoContableActionPerformed

    private void btbFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbFiltrarActionPerformed
       
    }//GEN-LAST:event_btbFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
ModeloDAO.LibroDiarioDao Ll = new  LibroDiarioDao();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaLibroDiario;
    public static javax.swing.JButton btbFiltrar;
    public static javax.swing.JButton btbVerAsientoContable;
    public static javax.swing.JButton btbVolveMenu;
    public static com.toedter.calendar.JDateChooser jDateDesde;
    public static com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
