/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_Libro_Contable;

import ModeloDAO.Libro_MayorDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adrian
 */
public class frm_LibroMayor extends javax.swing.JFrame {

    /**
     * Creates new form frm_LibroMayor
     */
    public frm_LibroMayor() throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle(" Libro Mayor");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        lM.MostrarLibro_Mayor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLibroMayor = new javax.swing.JTable();
        btbVolveMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        btbFiltarCuenta = new javax.swing.JButton();
        Fondo_Pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Libro Mayor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 20));

        TablaLibroMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaLibroMayor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 1200, 360));

        btbVolveMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolveMenu.setText("Volver");
        btbVolveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVolveMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btbVolveMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 654, 140, 40));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtrado por Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desde :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 100, -1));
        jPanel1.add(jDateDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 170, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hasta :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, -1, -1));
        jPanel1.add(jDateHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 180, 30));

        btbFiltarCuenta.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btbFiltarCuenta.setText("Filtrar");
        btbFiltarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbFiltarCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btbFiltarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 670, 120, -1));

        Fondo_Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/FondoCompleto.png"))); // NOI18N
        jPanel1.add(Fondo_Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1390, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 744));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbVolveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVolveMenuActionPerformed


   
    }//GEN-LAST:event_btbVolveMenuActionPerformed

    private void btbFiltarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbFiltarCuentaActionPerformed


    }//GEN-LAST:event_btbFiltarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
  
    ModeloDAO.Libro_MayorDao lM = new Libro_MayorDao();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo_Pantalla;
    public static javax.swing.JTable TablaLibroMayor;
    public static javax.swing.JButton btbFiltarCuenta;
    public static javax.swing.JButton btbVolveMenu;
    public static com.toedter.calendar.JDateChooser jDateDesde;
    public static com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
