/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_Libro_Contable;



/**
 *
 * @author Adrian
 */
public class frm_AsientoContable extends javax.swing.JFrame {

    /**
     * Creates new form frm_AsientoContable
     */
    public frm_AsientoContable()  {
        initComponents();
        setTitle("Asientos Contables");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAsiento = new javax.swing.JTable();
        btbAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        btbFiltrarAsientos = new javax.swing.JButton();
        Fondo_Pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Invenatrio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Asientos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 50, 120, -1));

        TablaAsiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaAsiento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 1220, 390));

        btbAtras.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Atras.png"))); // NOI18N
        btbAtras.setText("Atrás");
        btbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btbAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 120, 40));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtrado por Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desde :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, -1, -1));
        jPanel1.add(jDateDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 170, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hasta :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, -1, -1));
        jPanel1.add(jDateHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, 180, 30));

        btbFiltrarAsientos.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btbFiltrarAsientos.setText("Filtrar");
        btbFiltrarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbFiltrarAsientosActionPerformed(evt);
            }
        });
        jPanel1.add(btbFiltrarAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 680, 130, -1));

        Fondo_Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(Fondo_Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1380, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1377, 748));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAtrasActionPerformed

     
        

    }//GEN-LAST:event_btbAtrasActionPerformed

    private void btbFiltrarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbFiltrarAsientosActionPerformed

    }//GEN-LAST:event_btbFiltrarAsientosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo_Pantalla;
    public static javax.swing.JTable TablaAsiento;
    public static javax.swing.JButton btbAtras;
    public static javax.swing.JButton btbFiltrarAsientos;
    public static com.toedter.calendar.JDateChooser jDateDesde;
    public static com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
