/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Gestion_Productos;

import Modelo.Categoria;
import Modelo.Marca;
import ModeloDAO.CategoriaDao;
import ModeloDAO.MarcaDao;
import ModeloDAO.ProductoDao;
import Validacion.Validar_Producto;
import dictionary.AutoCorrectorGlobal;
import java.sql.SQLException;

/**
 *
 * @author avila
 */
public class Vista_Registro_Producto_Liquido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_Registro_Producto_Liquido.class.getName());

    /**
     * Creates new form Vista_Registro_Producto_Liquido
     */
    public Vista_Registro_Producto_Liquido() throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle("Registro de Producto Liquido");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
         
     
   
        btbConfirmarActualizacion.setVisible(false);
        btbCancelarActualizacion.setVisible(false);
   
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreProductoLiquido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipodeLiquido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboDensidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtViscosidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboCategoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboMarca = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarCategoria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBuscarMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRegistroLiquido = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarProductoLiquido = new javax.swing.JTextField();
        btbVolverMenu = new javax.swing.JButton();
        btbEliminar = new javax.swing.JButton();
        btbActualizar = new javax.swing.JButton();
        btbRegistrar = new javax.swing.JButton();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarActualizacion = new javax.swing.JButton();
        lblNombreLiquidoValidacion = new javax.swing.JLabel();
        lblNombreViscocidadValidacion = new javax.swing.JLabel();
        lblPresentacionValidacion = new javax.swing.JLabel();
        lblCategoriaValidacion = new javax.swing.JLabel();
        lblMarcaValidacion = new javax.swing.JLabel();
        lblTipoLiquidoVALIDACION = new javax.swing.JLabel();
        Fondo_Sistema = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro Producto Liquido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de Inventario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtNombreProductoLiquido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtNombreProductoLiquido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNombreProductoLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Liquido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtTipodeLiquido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtTipodeLiquido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTipodeLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 190, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Densidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jComboDensidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jComboDensidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Media", "Baja" }));
        jPanel1.add(jComboDensidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Viscosidad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 150, -1));

        txtViscosidad.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtViscosidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtViscosidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 160, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Presentación:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        txtPresentacion.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtPresentacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 160, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, -1, -1));

        jComboCategoria.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jPanel1.add(jComboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, 140, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Marca:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, 30));

        jPanel1.add(jComboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 140, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar:");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, -1, 30));

        txtBuscarCategoria.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 120, 110, 30));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buscar:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, -1, 30));

        txtBuscarMarca.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 183, 100, 30));

        TablaRegistroLiquido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaRegistroLiquido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaRegistroLiquido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 1220, 290));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Buscar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 300, -1, -1));

        txtBuscarProductoLiquido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoLiquido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProductoLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, 110, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, 150, -1));

        btbEliminar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btbEliminar.setText("Eliminar");
        jPanel1.add(btbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 670, -1, -1));

        btbActualizar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbActualizar.setText("Actualizar");
        jPanel1.add(btbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 670, -1, 30));

        btbRegistrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrar.setText("Registrar");
        jPanel1.add(btbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 670, 160, 30));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacion.setText("Confirmar ");
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 670, 160, -1));

        btbCancelarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActualizacion.setText("Cancelar");
        jPanel1.add(btbCancelarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, -1, -1));

        lblNombreLiquidoValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNombreLiquidoValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNombreLiquidoValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNombreLiquidoValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 320, 10));

        lblNombreViscocidadValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNombreViscocidadValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNombreViscocidadValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNombreViscocidadValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, 10));

        lblPresentacionValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblPresentacionValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblPresentacionValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblPresentacionValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 260, 20));

        lblCategoriaValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblCategoriaValidacion.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblCategoriaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 190, 10));

        lblMarcaValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblMarcaValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblMarcaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarcaValidacion.setToolTipText("");
        jPanel1.add(lblMarcaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 230, 20));

        lblTipoLiquidoVALIDACION.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblTipoLiquidoVALIDACION.setForeground(new java.awt.Color(255, 0, 0));
        lblTipoLiquidoVALIDACION.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTipoLiquidoVALIDACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 260, 20));

        Fondo_Sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(Fondo_Sistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1413, 746));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     Validacion.Validar_Producto validar_Producto = new Validar_Producto();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo_Sistema;
    public static javax.swing.JTable TablaRegistroLiquido;
    public static javax.swing.JButton btbActualizar;
    public static javax.swing.JButton btbCancelarActualizacion;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbEliminar;
    public static javax.swing.JButton btbRegistrar;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<Categoria> jComboCategoria;
    public static javax.swing.JComboBox<String> jComboDensidad;
    public static javax.swing.JComboBox<Marca> jComboMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel lblCategoriaValidacion;
    public static javax.swing.JLabel lblMarcaValidacion;
    public static javax.swing.JLabel lblNombreLiquidoValidacion;
    public static javax.swing.JLabel lblNombreViscocidadValidacion;
    public static javax.swing.JLabel lblPresentacionValidacion;
    public static javax.swing.JLabel lblTipoLiquidoVALIDACION;
    public static javax.swing.JTextField txtBuscarCategoria;
    public static javax.swing.JTextField txtBuscarMarca;
    public static javax.swing.JTextField txtBuscarProductoLiquido;
    public static javax.swing.JTextField txtNombreProductoLiquido;
    public static javax.swing.JTextField txtPresentacion;
    public static javax.swing.JTextField txtTipodeLiquido;
    public static javax.swing.JTextField txtViscosidad;
    // End of variables declaration//GEN-END:variables
}
