/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Gestion_Productos;

import Modelo.Categoria;
import Modelo.Marca;

/**
 *
 * @author avila
 */
public class Vista_Registrar_Producto_Solido extends javax.swing.JFrame {
    
   
    /**
     * Creates new form Vista_Registrar_Producto_Solido
     */
    public Vista_Registrar_Producto_Solido() {
        initComponents();
        setTitle("Registrar Producto Solido");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreProductoSolido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSolidoCompartibilidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboUnidaSolido = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCondicionSolido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboMarca = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtBuscarCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSolido = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btbRegistrarProductoSolido = new javax.swing.JButton();
        btbVolverMenu = new javax.swing.JButton();
        btbEliminarSolido = new javax.swing.JButton();
        btbActualizarSolido = new javax.swing.JButton();
        btbConfirmarActulizacion = new javax.swing.JButton();
        btbCancelarActuailizacion = new javax.swing.JButton();
        lblNombreSolidoValidavion = new javax.swing.JLabel();
        lblCompartibilidadValidacionSolido = new javax.swing.JLabel();
        lblCandicionValidacion = new javax.swing.JLabel();
        lblUnidadDeMedidaValidacion = new javax.swing.JLabel();
        lblCategoriaValidacion = new javax.swing.JLabel();
        lblMarcaValidacion = new javax.swing.JLabel();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro Producto Sólido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtNombreProductoSolido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtNombreProductoSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreProductoSolido.setToolTipText("");
        jPanel1.add(txtNombreProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 170, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Compartibilidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 30));

        txtSolidoCompartibilidad.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtSolidoCompartibilidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSolidoCompartibilidad.addActionListener(this::txtSolidoCompartibilidadActionPerformed);
        jPanel1.add(txtSolidoCompartibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 230, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unidad De Medida:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jComboUnidaSolido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jComboUnidaSolido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kit", "Par", "Unidad", "Juego" }));
        jPanel1.add(jComboUnidaSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 140, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Condición:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        txtCondicionSolido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtCondicionSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCondicionSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 140, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, -1));

        jPanel1.add(jComboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, 130, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, -1, -1));

        jComboMarca.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 130, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 120, -1, 30));

        txtBuscarCategoria.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        txtBuscarCategoria.addActionListener(this::txtBuscarCategoriaActionPerformed);
        jPanel1.add(txtBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 120, 80, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 200, -1, 30));

        txtBuscarMarca.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        txtBuscarMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 200, 80, 30));

        TablaSolido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        TablaSolido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaSolido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 1280, 270));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buscar:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 271, -1, 40));

        txtBuscarProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 280, 90, 30));

        btbRegistrarProductoSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrarProductoSolido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrarProductoSolido.setText("Registrar");
        jPanel1.add(btbRegistrarProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 660, 150, 40));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 130, 40));

        btbEliminarSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbEliminarSolido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btbEliminarSolido.setText("Eliminar");
        btbEliminarSolido.addActionListener(this::btbEliminarSolidoActionPerformed);
        jPanel1.add(btbEliminarSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 140, 40));

        btbActualizarSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbActualizarSolido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbActualizarSolido.setText("Actualizar");
        btbActualizarSolido.setToolTipText("");
        jPanel1.add(btbActualizarSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 660, -1, 40));

        btbConfirmarActulizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActulizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActulizacion.setText("Confirmar");
        btbConfirmarActulizacion.addActionListener(this::btbConfirmarActulizacionActionPerformed);
        jPanel1.add(btbConfirmarActulizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, -1, 40));

        btbCancelarActuailizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarActuailizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActuailizacion.setText("Cancelar");
        jPanel1.add(btbCancelarActuailizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, 140, 40));

        lblNombreSolidoValidavion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNombreSolidoValidavion.setForeground(new java.awt.Color(255, 0, 0));
        lblNombreSolidoValidavion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNombreSolidoValidavion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 310, 20));

        lblCompartibilidadValidacionSolido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblCompartibilidadValidacionSolido.setForeground(new java.awt.Color(255, 0, 0));
        lblCompartibilidadValidacionSolido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCompartibilidadValidacionSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 320, 20));

        lblCandicionValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblCandicionValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblCandicionValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCandicionValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 250, 20));

        lblUnidadDeMedidaValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblUnidadDeMedidaValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblUnidadDeMedidaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblUnidadDeMedidaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 190, 20));

        lblCategoriaValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblCategoriaValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblCategoriaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCategoriaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 170, 20));

        lblMarcaValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblMarcaValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblMarcaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblMarcaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 230, 20));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1540, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1537, 746));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSolidoCompartibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolidoCompartibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolidoCompartibilidadActionPerformed

    private void txtBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCategoriaActionPerformed

    private void btbEliminarSolidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEliminarSolidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbEliminarSolidoActionPerformed

    private void btbConfirmarActulizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConfirmarActulizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbConfirmarActulizacionActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JTable TablaSolido;
    public static javax.swing.JButton btbActualizarSolido;
    public static javax.swing.JButton btbCancelarActuailizacion;
    public static javax.swing.JButton btbConfirmarActulizacion;
    public static javax.swing.JButton btbEliminarSolido;
    public static javax.swing.JButton btbRegistrarProductoSolido;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<Categoria> jComboCategoria;
    public static javax.swing.JComboBox<Marca> jComboMarca;
    public static javax.swing.JComboBox<String> jComboUnidaSolido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCandicionValidacion;
    public static javax.swing.JLabel lblCategoriaValidacion;
    public static javax.swing.JLabel lblCompartibilidadValidacionSolido;
    public static javax.swing.JLabel lblMarcaValidacion;
    public static javax.swing.JLabel lblNombreSolidoValidavion;
    public static javax.swing.JLabel lblUnidadDeMedidaValidacion;
    public static javax.swing.JTextField txtBuscarCategoria;
    public static javax.swing.JTextField txtBuscarMarca;
    public static javax.swing.JTextField txtBuscarProducto;
    public static javax.swing.JTextField txtCondicionSolido;
    public static javax.swing.JTextField txtNombreProductoSolido;
    public static javax.swing.JTextField txtSolidoCompartibilidad;
    // End of variables declaration//GEN-END:variables
}
