/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Gestion_Productos;

import Modelo.Categoria;
import Modelo.Marca;

/**
 *
 * @author avila
 */
public class Vista_Registrar_Producto_Unidad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_Registrar_Producto_Unidad.class.getName());

    /**
     * Creates new form Vista_Registrar_Producto_Unidad
     */
    public Vista_Registrar_Producto_Unidad() {
        initComponents();
        setTitle("Registrar Producto Unidad");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUnidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCompartibilidadUnidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboxCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarCategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroSerial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JcomoBoxUnidadDeMedida = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JcomoBoxMarca = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEspecificacionTecnica = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUnidad = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarProductoUnidad = new javax.swing.JTextField();
        btbRegistrarProdutoUnidad = new javax.swing.JButton();
        btbActualizarProducto = new javax.swing.JButton();
        btbVolverMenu = new javax.swing.JButton();
        btbEliminarProducto = new javax.swing.JButton();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarActualizacion = new javax.swing.JButton();
        lblNombreUnidadValidacion = new javax.swing.JLabel();
        lblCompartibilidaUnidadValidacion = new javax.swing.JLabel();
        lblCategoriaUnidadValidacion = new javax.swing.JLabel();
        lblNumeroSerialValidacion = new javax.swing.JLabel();
        lblUnidadMedidaValidacion = new javax.swing.JLabel();
        lblMarcaValidscion = new javax.swing.JLabel();
        lblEspecificaionesValidacion = new javax.swing.JLabel();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Producto Unidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtNombreUnidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtNombreUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNombreUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 170, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Compatibilidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        txtCompartibilidadUnidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCompartibilidadUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCompartibilidadUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 220, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));

        jComboxCategoria.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 120, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, -1, 30));

        txtBuscarCategoria.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 90, 80, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Número serial:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtNumeroSerial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtNumeroSerial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNumeroSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 160, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Unidad De Medida:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        JcomoBoxUnidadDeMedida.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        JcomoBoxUnidadDeMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kit", "Par", "Unidad", "Juego" }));
        jPanel1.add(JcomoBoxUnidadDeMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 200, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Marca:");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, -1, -1));

        JcomoBoxMarca.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(JcomoBoxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 120, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 170, -1, 30));

        txtBuscarMarca.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, 80, 30));

        txtEspecificacionTecnica.setColumns(20);
        txtEspecificacionTecnica.setRows(5);
        jScrollPane1.setViewportView(txtEspecificacionTecnica);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, 60));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Especificaciones tecnica:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        TablaUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        TablaUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaUnidad);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 1260, 270));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Buscar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 320, -1, -1));

        txtBuscarProductoUnidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarProductoUnidad.addActionListener(this::txtBuscarProductoUnidadActionPerformed);
        jPanel1.add(txtBuscarProductoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 320, 90, -1));

        btbRegistrarProdutoUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrarProdutoUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrarProdutoUnidad.setText("Registrar");
        jPanel1.add(btbRegistrarProdutoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 670, 140, 30));

        btbActualizarProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbActualizarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbActualizarProducto.setText("Actualizar");
        jPanel1.add(btbActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, -1, 30));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 130, -1));

        btbEliminarProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btbEliminarProducto.setText("Eliminar");
        jPanel1.add(btbEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, 130, -1));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacion.setText("Confirmar");
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 150, 30));

        btbCancelarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActualizacion.setText("Cancelar");
        jPanel1.add(btbCancelarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 670, 150, 30));

        lblNombreUnidadValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNombreUnidadValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNombreUnidadValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNombreUnidadValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 250, 20));

        lblCompartibilidaUnidadValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblCompartibilidaUnidadValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblCompartibilidaUnidadValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCompartibilidaUnidadValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 260, 20));

        lblCategoriaUnidadValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblCategoriaUnidadValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblCategoriaUnidadValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCategoriaUnidadValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 230, 20));

        lblNumeroSerialValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNumeroSerialValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNumeroSerialValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNumeroSerialValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, 20));

        lblUnidadMedidaValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblUnidadMedidaValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblUnidadMedidaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidadMedidaValidacion.setToolTipText("");
        jPanel1.add(lblUnidadMedidaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 260, 20));

        lblMarcaValidscion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblMarcaValidscion.setForeground(new java.awt.Color(255, 0, 0));
        lblMarcaValidscion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblMarcaValidscion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 190, 20));

        lblEspecificaionesValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblEspecificaionesValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblEspecificaionesValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblEspecificaionesValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 310, 20));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        FondoPantalla.setText("jLabel1");
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductoUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoUnidadActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JComboBox<Marca> JcomoBoxMarca;
    public static javax.swing.JComboBox<String> JcomoBoxUnidadDeMedida;
    public static javax.swing.JTable TablaUnidad;
    public static javax.swing.JButton btbActualizarProducto;
    public static javax.swing.JButton btbCancelarActualizacion;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbEliminarProducto;
    public static javax.swing.JButton btbRegistrarProdutoUnidad;
    public static volatile javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<Categoria> jComboxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblCategoriaUnidadValidacion;
    public static javax.swing.JLabel lblCompartibilidaUnidadValidacion;
    public static javax.swing.JLabel lblEspecificaionesValidacion;
    public static javax.swing.JLabel lblMarcaValidscion;
    public static javax.swing.JLabel lblNombreUnidadValidacion;
    public static javax.swing.JLabel lblNumeroSerialValidacion;
    public static javax.swing.JLabel lblUnidadMedidaValidacion;
    public static javax.swing.JTextField txtBuscarCategoria;
    public static javax.swing.JTextField txtBuscarMarca;
    public static javax.swing.JTextField txtBuscarProductoUnidad;
    public static javax.swing.JTextField txtCompartibilidadUnidad;
    public static javax.swing.JTextArea txtEspecificacionTecnica;
    public static javax.swing.JTextField txtNombreUnidad;
    public static javax.swing.JTextField txtNumeroSerial;
    // End of variables declaration//GEN-END:variables
}
