/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_GestionInventario;

import Modelo.Almacen;
import Modelo.Producto;
import Modelo.Proveedor;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class InventarioLiquido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventarioLiquido.class.getName());

    /**
     * Creates new form InventarioLiquido
     */
    public InventarioLiquido() {
        initComponents();
        setTitle("Inventario Liquido");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboProductoLiquido = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTipoProductoLiquido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadActual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStockMaximo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboProveedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarProveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboUbicacion = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarUbicacion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCostoUnitario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jDateFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboCuentaDebitar = new javax.swing.JComboBox<>();
        jComboCuentaAcreditar = new javax.swing.JComboBox<>();
        JcroPanelPrincipal = new javax.swing.JScrollPane();
        TablaLiquido = new javax.swing.JTable();
        lblStockCritico = new javax.swing.JLabel();
        lblStockMedio = new javax.swing.JLabel();
        lblStockEstable = new javax.swing.JLabel();
        btbVolverMenu = new javax.swing.JButton();
        btbModificar = new javax.swing.JButton();
        btbHistorialMovimiento = new javax.swing.JButton();
        btbInformacionLote = new javax.swing.JButton();
        btbRegistrar = new javax.swing.JButton();
        btbOcultarHistorial = new javax.swing.JButton();
        jScrollPaneHistorial = new javax.swing.JScrollPane();
        TablaHistorial = new javax.swing.JTable();
        jScrollPaneInformacionLote = new javax.swing.JScrollPane();
        TablaLote = new javax.swing.JTable();
        btbOcultarLote = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtBuscarProductoLiquidoTabla = new javax.swing.JTextField();
        txtBuscarLote = new javax.swing.JTextField();
        txtBuscarHistorial = new javax.swing.JTextField();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarActualizacion = new javax.swing.JButton();
        btbModificarLote = new javax.swing.JButton();
        btbConfirmarModificacionLote = new javax.swing.JButton();
        btbCancelarModificacionLote = new javax.swing.JButton();
        lblValidarProducto = new javax.swing.JLabel();
        lblValidarCantidad = new javax.swing.JLabel();
        lblValidadStockMaximo = new javax.swing.JLabel();
        lblValidarStockMinimo = new javax.swing.JLabel();
        lblValidarProveedor = new javax.swing.JLabel();
        lblValidarUbicacion = new javax.swing.JLabel();
        lblvValidarCostoUnitario = new javax.swing.JLabel();
        lblValidarPorcentaje = new javax.swing.JLabel();
        lblValidarPrecioVenta = new javax.swing.JLabel();
        lblValidarFechaVencimiento = new javax.swing.JLabel();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario Liquido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Producto:");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jComboProductoLiquido.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jComboProductoLiquido.addActionListener(this::jComboProductoLiquidoActionPerformed);
        jPanel1.add(jComboProductoLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 420, 20));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 30));

        txtBuscarProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 77, 70, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        txtTipoProductoLiquido.setEditable(false);
        txtTipoProductoLiquido.setBackground(new java.awt.Color(0, 0, 0));
        txtTipoProductoLiquido.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtTipoProductoLiquido.setForeground(new java.awt.Color(255, 255, 51));
        txtTipoProductoLiquido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProductoLiquido.setText("Liquido");
        jPanel1.add(txtTipoProductoLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtCantidadActual.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidadActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock Máximo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtStockMaximo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtStockMaximo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStockMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 100, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stock Minimo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtStockMinimo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtStockMinimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Proveedor:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 180, 110, 20));

        jComboProveedor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jComboProveedor.addActionListener(this::jComboProveedorActionPerformed);
        jPanel1.add(jComboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, 20));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar:");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        txtBuscarProveedor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarProveedor.setToolTipText("");
        jPanel1.add(txtBuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 70, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Ubicación:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        jComboUbicacion.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jPanel1.add(jComboUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 430, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Buscar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, -1, 20));

        txtBuscarUbicacion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarUbicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 80, 80, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Costo Unitario:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 160, -1));

        txtCostoUnitario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCostoUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCostoUnitario.addActionListener(this::txtCostoUnitarioActionPerformed);
        jPanel1.add(txtCostoUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 80, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("% :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, -1, -1));

        txtPorcentaje.setEditable(false);
        txtPorcentaje.setBackground(new java.awt.Color(255, 255, 51));
        txtPorcentaje.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPorcentaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPorcentaje.setText("30");
        jPanel1.add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 180, 50, -1));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Precio Venta:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, -1, -1));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBackground(new java.awt.Color(153, 255, 153));
        txtPrecioVenta.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 100, -1));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Fecha V:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, 20));
        jPanel1.add(jDateFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 170, 30));

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cuanta a debitar:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cuenta a acreditar:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, 20));

        jComboCuentaDebitar.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jPanel1.add(jComboCuentaDebitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 230, 20));

        jComboCuentaAcreditar.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jComboCuentaAcreditar.addActionListener(this::jComboCuentaAcreditarActionPerformed);
        jPanel1.add(jComboCuentaAcreditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 210, 20));

        TablaLiquido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        TablaLiquido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JcroPanelPrincipal.setViewportView(TablaLiquido);

        jPanel1.add(JcroPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 420, 1290, 210));

        lblStockCritico.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblStockCritico.setForeground(new java.awt.Color(255, 255, 255));
        lblStockCritico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockCritico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Rojo.png"))); // NOI18N
        lblStockCritico.setText("Stock Critico");
        jPanel1.add(lblStockCritico, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        lblStockMedio.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblStockMedio.setForeground(new java.awt.Color(255, 255, 255));
        lblStockMedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Amarrilo.png"))); // NOI18N
        lblStockMedio.setText("Stock Medio");
        jPanel1.add(lblStockMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        lblStockEstable.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblStockEstable.setForeground(new java.awt.Color(255, 255, 255));
        lblStockEstable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-verde.png"))); // NOI18N
        lblStockEstable.setText("Stock Estable");
        jPanel1.add(lblStockEstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Menu");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 682, 120, 30));

        btbModificar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbModificar.setText("Modificar");
        jPanel1.add(btbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, -1, 30));

        btbHistorialMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbHistorialMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbHistorialMovimiento.setText("Historial de Movimiento");
        jPanel1.add(btbHistorialMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, -1, 30));

        btbInformacionLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbInformacionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veer Lote.png"))); // NOI18N
        btbInformacionLote.setText("Información de Lote");
        jPanel1.add(btbInformacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 680, 240, 30));

        btbRegistrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrar.setText("Registrar");
        jPanel1.add(btbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 680, 140, -1));

        btbOcultarHistorial.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btbOcultarHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbOcultarHistorial.setText("Ocultar Historial");
        jPanel1.add(btbOcultarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, 240, 30));

        TablaHistorial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneHistorial.setViewportView(TablaHistorial);

        jPanel1.add(jScrollPaneHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 420, 1290, 210));

        TablaLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneInformacionLote.setViewportView(TablaLote);

        jPanel1.add(jScrollPaneInformacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 420, 1290, 210));

        btbOcultarLote.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btbOcultarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbOcultarLote.setText("Ocultar Lote");
        jPanel1.add(btbOcultarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, 220, 30));

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Buscar:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, -1, -1));

        txtBuscarProductoLiquidoTabla.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoLiquidoTabla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProductoLiquidoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 390, 110, -1));

        txtBuscarLote.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 390, 110, -1));

        txtBuscarHistorial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarHistorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 390, 110, -1));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacion.setText("Confirmar Actualización");
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, 260, 30));

        btbCancelarActualizacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btbCancelarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActualizacion.setText("Cancelar");
        btbCancelarActualizacion.setToolTipText("");
        jPanel1.add(btbCancelarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 680, 150, 30));

        btbModificarLote.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btbModificarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbModificarLote.setText("Modificar Lote");
        btbModificarLote.addActionListener(this::btbModificarLoteActionPerformed);
        jPanel1.add(btbModificarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 190, 30));

        btbConfirmarModificacionLote.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btbConfirmarModificacionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarModificacionLote.setText("Confirmar Modificación");
        jPanel1.add(btbConfirmarModificacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, 230, 30));

        btbCancelarModificacionLote.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btbCancelarModificacionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarModificacionLote.setText("Cancelar");
        jPanel1.add(btbCancelarModificacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 680, 150, 30));

        lblValidarProducto.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarProducto.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidarProducto.setToolTipText("");
        jPanel1.add(lblValidarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 420, 20));

        lblValidarCantidad.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarCantidad.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, 20));

        lblValidadStockMaximo.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidadStockMaximo.setForeground(new java.awt.Color(255, 0, 0));
        lblValidadStockMaximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidadStockMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 264, 150, 20));

        lblValidarStockMinimo.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarStockMinimo.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarStockMinimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidarStockMinimo.setToolTipText("");
        jPanel1.add(lblValidarStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 140, 20));

        lblValidarProveedor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarProveedor.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 190, 20));

        lblValidarUbicacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarUbicacion.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 440, 20));

        lblvValidarCostoUnitario.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblvValidarCostoUnitario.setForeground(new java.awt.Color(255, 0, 0));
        lblvValidarCostoUnitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblvValidarCostoUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 204, 130, 20));

        lblValidarPorcentaje.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarPorcentaje.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, 70, 20));

        lblValidarPrecioVenta.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarPrecioVenta.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarPrecioVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 210, 160, 30));

        lblValidarFechaVencimiento.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarFechaVencimiento.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarFechaVencimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 200, 20));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1387, 744));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboProductoLiquidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboProductoLiquidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProductoLiquidoActionPerformed

    private void jComboProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProveedorActionPerformed

    private void txtCostoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoUnitarioActionPerformed

    private void jComboCuentaAcreditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCuentaAcreditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCuentaAcreditarActionPerformed

    private void btbModificarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbModificarLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbModificarLoteActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JScrollPane JcroPanelPrincipal;
    public static javax.swing.JTable TablaHistorial;
    public static javax.swing.JTable TablaLiquido;
    public static javax.swing.JTable TablaLote;
    public static javax.swing.JButton btbCancelarActualizacion;
    public static javax.swing.JButton btbCancelarModificacionLote;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbConfirmarModificacionLote;
    public static javax.swing.JButton btbHistorialMovimiento;
    public static javax.swing.JButton btbInformacionLote;
    public static javax.swing.JButton btbModificar;
    public static javax.swing.JButton btbModificarLote;
    public static javax.swing.JButton btbOcultarHistorial;
    public static javax.swing.JButton btbOcultarLote;
    public static javax.swing.JButton btbRegistrar;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<cuenta> jComboCuentaAcreditar;
    public static javax.swing.JComboBox<cuenta> jComboCuentaDebitar;
    public static javax.swing.JComboBox<Producto> jComboProductoLiquido;
    public static javax.swing.JComboBox<Proveedor> jComboProveedor;
    public static javax.swing.JComboBox<Almacen> jComboUbicacion;
    public static com.toedter.calendar.JDateChooser jDateFechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPaneHistorial;
    public static javax.swing.JScrollPane jScrollPaneInformacionLote;
    public static javax.swing.JLabel lblStockCritico;
    public static javax.swing.JLabel lblStockEstable;
    public static javax.swing.JLabel lblStockMedio;
    public static javax.swing.JLabel lblValidadStockMaximo;
    public static javax.swing.JLabel lblValidarCantidad;
    public static javax.swing.JLabel lblValidarFechaVencimiento;
    public static javax.swing.JLabel lblValidarPorcentaje;
    public static javax.swing.JLabel lblValidarPrecioVenta;
    public static javax.swing.JLabel lblValidarProducto;
    public static javax.swing.JLabel lblValidarProveedor;
    public static javax.swing.JLabel lblValidarStockMinimo;
    public static javax.swing.JLabel lblValidarUbicacion;
    public static javax.swing.JLabel lblvValidarCostoUnitario;
    public static javax.swing.JTextField txtBuscarHistorial;
    public static javax.swing.JTextField txtBuscarLote;
    public static javax.swing.JTextField txtBuscarProducto;
    public static javax.swing.JTextField txtBuscarProductoLiquidoTabla;
    public static javax.swing.JTextField txtBuscarProveedor;
    public static javax.swing.JTextField txtBuscarUbicacion;
    public static javax.swing.JTextField txtCantidadActual;
    public static javax.swing.JTextField txtCostoUnitario;
    public static javax.swing.JTextField txtPorcentaje;
    public static javax.swing.JTextField txtPrecioVenta;
    public static javax.swing.JTextField txtStockMaximo;
    public static javax.swing.JTextField txtStockMinimo;
    public static javax.swing.JTextField txtTipoProductoLiquido;
    // End of variables declaration//GEN-END:variables
}
