/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_GestionInventario;

import Modelo.Almacen;
import Modelo.Producto;
import Modelo.Proveedor;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class InventarioSolido extends javax.swing.JFrame {
    
   

    /**
     * Creates new form InventarioSolido
     */
    public InventarioSolido() {
        initComponents();
        setTitle("");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipoProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboProductoSolido = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarProducroSolido = new javax.swing.JTextField();
        txtCantidadSolido = new javax.swing.JTextField();
        txtStoxkMaximo = new javax.swing.JTextField();
        txtStockMinimo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarProveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCuentaDebitar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCuentaAcreditar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboUbicacionSolido = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtCostoUUnitario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPorcentajeSolido = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrecioVentaSolido = new javax.swing.JTextField();
        jScrollPaneSolidoPrincipal = new javax.swing.JScrollPane();
        TablaSolido = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btbVolverMenu = new javax.swing.JButton();
        btbModificar = new javax.swing.JButton();
        btbHistorialDeMovimientoSolido = new javax.swing.JButton();
        btbInformacionDeLote = new javax.swing.JButton();
        btbRegistrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtBuscarUbicacion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtBuscarProductoEntabla = new javax.swing.JTextField();
        jScrollPaneSolidoHistorial = new javax.swing.JScrollPane();
        TablaHistorialSolido = new javax.swing.JTable();
        btbOcultarHistorial = new javax.swing.JButton();
        txtBuscarHistorial = new javax.swing.JTextField();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarActualizacion = new javax.swing.JButton();
        jScrollPaneSolidoInformacionLote = new javax.swing.JScrollPane();
        TablaLote = new javax.swing.JTable();
        btbOcultarLote = new javax.swing.JButton();
        txtBuscarLote = new javax.swing.JTextField();
        btbModificarLote = new javax.swing.JButton();
        btbConfirmarActualizacionLote = new javax.swing.JButton();
        btbCancelarActualizcionLote = new javax.swing.JButton();
        lblValidarProductoSolido = new javax.swing.JLabel();
        lblValidarAlmacenSolido = new javax.swing.JLabel();
        lblValidarProveedor = new javax.swing.JLabel();
        lblValidarCantidadActual = new javax.swing.JLabel();
        lblValidarStocMaximo = new javax.swing.JLabel();
        lblValidarStockMinimo = new javax.swing.JLabel();
        lblValidarPorcentaje = new javax.swing.JLabel();
        lblValidarCostoUnitario = new javax.swing.JLabel();
        lblValidarPrecioVenta = new javax.swing.JLabel();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario Solido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 40));

        txtTipoProducto.setEditable(false);
        txtTipoProducto.setBackground(new java.awt.Color(0, 0, 0));
        txtTipoProducto.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtTipoProducto.setForeground(new java.awt.Color(0, 255, 51));
        txtTipoProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProducto.setText("Solido");
        jPanel1.add(txtTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 110, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stock Máximo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock Minimo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jComboProductoSolido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 430, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 80, 20));

        txtBuscarProducroSolido.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtBuscarProducroSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProducroSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 90, -1));

        txtCantidadSolido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidadSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidadSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 80, -1));

        txtStoxkMaximo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtStoxkMaximo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStoxkMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 80, -1));

        txtStockMinimo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtStockMinimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 80, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Proveedor:");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jComboBoxProveedor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboBoxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 130, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        txtBuscarProveedor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cuenta a debitar:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jComboBoxCuentaDebitar.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jPanel1.add(jComboBoxCuentaDebitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 240, 240, 20));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cuenta a acreditar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jComboBoxCuentaAcreditar.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jPanel1.add(jComboBoxCuentaAcreditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 240, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ubicación:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, -1));

        jComboUbicacionSolido.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jPanel1.add(jComboUbicacionSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 410, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Costo Unitario:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        txtCostoUUnitario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCostoUUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCostoUUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 60, -1));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("% :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 30, 20));

        txtPorcentajeSolido.setEditable(false);
        txtPorcentajeSolido.setBackground(new java.awt.Color(255, 255, 0));
        txtPorcentajeSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPorcentajeSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPorcentajeSolido.setText("30");
        jPanel1.add(txtPorcentajeSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 230, 50, -1));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 255, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Precio Venta:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, -1, -1));

        txtPrecioVentaSolido.setEditable(false);
        txtPrecioVentaSolido.setBackground(new java.awt.Color(0, 255, 0));
        txtPrecioVentaSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPrecioVentaSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVentaSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 230, 90, -1));

        TablaSolido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaSolido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSolidoPrincipal.setViewportView(TablaSolido);

        jPanel1.add(jScrollPaneSolidoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 1300, 220));

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Rojo.png"))); // NOI18N
        jLabel17.setText("Stock Critico");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 365, -1, 30));

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Amarrilo.png"))); // NOI18N
        jLabel18.setText("Stock Medio");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, 40));

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-verde.png"))); // NOI18N
        jLabel19.setText("Stock Estable");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, 40));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, 30));

        btbModificar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbModificar.setText("Modificar");
        jPanel1.add(btbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, 160, 30));

        btbHistorialDeMovimientoSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbHistorialDeMovimientoSolido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbHistorialDeMovimientoSolido.setText("Historial de Movimiento");
        jPanel1.add(btbHistorialDeMovimientoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, -1, 30));

        btbInformacionDeLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbInformacionDeLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veer Lote.png"))); // NOI18N
        btbInformacionDeLote.setText("Información de Lote");
        jPanel1.add(btbInformacionDeLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 670, -1, 30));

        btbRegistrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrar.setText("Registrar");
        btbRegistrar.setToolTipText("");
        jPanel1.add(btbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 667, 140, 30));

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Buscar:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 90, -1, -1));

        txtBuscarUbicacion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarUbicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 90, 80, -1));

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Buscar:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 360, -1, -1));

        txtBuscarProductoEntabla.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoEntabla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProductoEntabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 360, 100, -1));

        TablaHistorialSolido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaHistorialSolido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSolidoHistorial.setViewportView(TablaHistorialSolido);

        jPanel1.add(jScrollPaneSolidoHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 1300, 220));

        btbOcultarHistorial.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbOcultarHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbOcultarHistorial.setText("Ocultar Historial");
        jPanel1.add(btbOcultarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 240, 30));

        txtBuscarHistorial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarHistorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 360, 100, -1));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacion.setText("Confirmar Modificación");
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 250, 30));

        btbCancelarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActualizacion.setText("Cancelar");
        jPanel1.add(btbCancelarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 670, 190, 30));

        TablaLote.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSolidoInformacionLote.setViewportView(TablaLote);

        jPanel1.add(jScrollPaneSolidoInformacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 1300, 220));

        btbOcultarLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbOcultarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbOcultarLote.setText("Ocultar Lote");
        jPanel1.add(btbOcultarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 670, -1, 30));

        txtBuscarLote.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 360, 100, -1));

        btbModificarLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbModificarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbModificarLote.setText("Modificar");
        jPanel1.add(btbModificarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 160, 30));

        btbConfirmarActualizacionLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacionLote.setText("Confirmar Modificación");
        jPanel1.add(btbConfirmarActualizacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 250, 30));

        btbCancelarActualizcionLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarActualizcionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActualizcionLote.setText("Cancelar");
        jPanel1.add(btbCancelarActualizcionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 673, 200, 30));

        lblValidarProductoSolido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarProductoSolido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarProductoSolido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 470, 20));

        lblValidarAlmacenSolido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarAlmacenSolido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarAlmacenSolido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarAlmacenSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 410, 20));

        lblValidarProveedor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarProveedor.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 190, 20));

        lblValidarCantidadActual.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarCantidadActual.setForeground(new java.awt.Color(255, 51, 51));
        lblValidarCantidadActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarCantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 206, 140, 20));

        lblValidarStocMaximo.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarStocMaximo.setForeground(new java.awt.Color(255, 51, 51));
        lblValidarStocMaximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarStocMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, 20));

        lblValidarStockMinimo.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarStockMinimo.setForeground(new java.awt.Color(255, 51, 51));
        lblValidarStockMinimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 150, 20));

        lblValidarPorcentaje.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarPorcentaje.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1013, 256, 90, 20));

        lblValidarCostoUnitario.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarCostoUnitario.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarCostoUnitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarCostoUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 140, 20));

        lblValidarPrecioVenta.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarPrecioVenta.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarPrecioVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 260, 130, 20));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1389, 742));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JTable TablaHistorialSolido;
    public static javax.swing.JTable TablaLote;
    public static javax.swing.JTable TablaSolido;
    public static javax.swing.JButton btbCancelarActualizacion;
    public static javax.swing.JButton btbCancelarActualizcionLote;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbConfirmarActualizacionLote;
    public static javax.swing.JButton btbHistorialDeMovimientoSolido;
    public static javax.swing.JButton btbInformacionDeLote;
    public static javax.swing.JButton btbModificar;
    public static javax.swing.JButton btbModificarLote;
    public static javax.swing.JButton btbOcultarHistorial;
    public static javax.swing.JButton btbOcultarLote;
    public static javax.swing.JButton btbRegistrar;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaAcreditar;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaDebitar;
    public static javax.swing.JComboBox<Proveedor> jComboBoxProveedor;
    public static javax.swing.JComboBox<Producto> jComboProductoSolido;
    public static javax.swing.JComboBox<Almacen> jComboUbicacionSolido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPaneSolidoHistorial;
    public static javax.swing.JScrollPane jScrollPaneSolidoInformacionLote;
    public static javax.swing.JScrollPane jScrollPaneSolidoPrincipal;
    public static javax.swing.JLabel lblValidarAlmacenSolido;
    public static javax.swing.JLabel lblValidarCantidadActual;
    public static javax.swing.JLabel lblValidarCostoUnitario;
    public static javax.swing.JLabel lblValidarPorcentaje;
    public static javax.swing.JLabel lblValidarPrecioVenta;
    public static javax.swing.JLabel lblValidarProductoSolido;
    public static javax.swing.JLabel lblValidarProveedor;
    public static javax.swing.JLabel lblValidarStocMaximo;
    public static javax.swing.JLabel lblValidarStockMinimo;
    public static javax.swing.JTextField txtBuscarHistorial;
    public static javax.swing.JTextField txtBuscarLote;
    public static javax.swing.JTextField txtBuscarProducroSolido;
    public static javax.swing.JTextField txtBuscarProductoEntabla;
    public static javax.swing.JTextField txtBuscarProveedor;
    public static javax.swing.JTextField txtBuscarUbicacion;
    public static javax.swing.JTextField txtCantidadSolido;
    public static javax.swing.JTextField txtCostoUUnitario;
    public static javax.swing.JTextField txtPorcentajeSolido;
    public static javax.swing.JTextField txtPrecioVentaSolido;
    public static javax.swing.JTextField txtStockMinimo;
    public static javax.swing.JTextField txtStoxkMaximo;
    public static javax.swing.JTextField txtTipoProducto;
    // End of variables declaration//GEN-END:variables
}
