/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_GestionInventario;

import Modelo.Almacen;
import Modelo.Producto;
import Modelo.Proveedor;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class InventarioUnidad extends javax.swing.JFrame {
    
   

    /**
     * Creates new form InventarioUnidad
     */
    public InventarioUnidad() {
        initComponents();
        setTitle("Inventario Unidad");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipoProductoUnidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboProductoUnidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarProductoCombox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStockMaximo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarProveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCuantDebitar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCuentaAcreditar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxUbicacion = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtBuscarUbicacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCostoUnitario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jScrollPanePrincipal = new javax.swing.JScrollPane();
        TablaUnidad = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtBuscarProductoEnTABLA = new javax.swing.JTextField();
        btbVolverMenu = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btbModificar = new javax.swing.JButton();
        btbInofrmacionLote = new javax.swing.JButton();
        btbRegistrar = new javax.swing.JButton();
        btbHistorialMovimiento = new javax.swing.JButton();
        btbOcultarHistorial = new javax.swing.JButton();
        jScrollPaneHistorialMovimiento = new javax.swing.JScrollPane();
        TablaHistorialMovimienrto = new javax.swing.JTable();
        txtBuscarHistorial = new javax.swing.JTextField();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarModificaion = new javax.swing.JButton();
        jScrollPaneInformacionLote = new javax.swing.JScrollPane();
        TablaLote = new javax.swing.JTable();
        btbOcultarLote = new javax.swing.JButton();
        txtBuscarLote = new javax.swing.JTextField();
        btbModificarLote = new javax.swing.JButton();
        btbConfirmaModificacionLote = new javax.swing.JButton();
        btbCancelarModificacionLote = new javax.swing.JButton();
        lblValidaProductoUnidad = new javax.swing.JLabel();
        lblValidarProveedorUnida = new javax.swing.JLabel();
        lblValidarAlamcenUnidad = new javax.swing.JLabel();
        lblValidarCantidaUnidad = new javax.swing.JLabel();
        lblValidarStockMaximoUnida = new javax.swing.JLabel();
        lblValidarStockMinimo = new javax.swing.JLabel();
        lblValidarPorcentaje = new javax.swing.JLabel();
        lblValidarCostoUnitario = new javax.swing.JLabel();
        lblValidarPrecioVenta = new javax.swing.JLabel();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario Unidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtTipoProductoUnidad.setEditable(false);
        txtTipoProductoUnidad.setBackground(new java.awt.Color(51, 51, 255));
        txtTipoProductoUnidad.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtTipoProductoUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProductoUnidad.setText("Unidad");
        jPanel1.add(txtTipoProductoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 110, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jComboProductoUnidad.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboProductoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 390, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        txtBuscarProductoCombox.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoCombox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarProductoCombox.setToolTipText("");
        jPanel1.add(txtBuscarProductoCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 80, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txtCantidadProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidadProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 70, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock Máximo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtStockMaximo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtStockMaximo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStockMaximo.setToolTipText("");
        jPanel1.add(txtStockMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stock Minimo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtStockMinimo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtStockMinimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Proveedor:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jComboBoxProveedor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(jComboBoxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 130, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        txtBuscarProveedor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cuenta a debitar:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jComboBoxCuantDebitar.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jPanel1.add(jComboBoxCuantDebitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 240, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cuenta a acreditar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 180, -1));

        jComboBoxCuentaAcreditar.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jPanel1.add(jComboBoxCuentaAcreditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 220, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ubicación:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, -1));

        jComboBoxUbicacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboBoxUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 440, 30));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Buscar:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 90, -1, -1));

        txtBuscarUbicacion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarUbicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 90, 70, -1));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Costo Unitario:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, -1, -1));

        txtCostoUnitario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCostoUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCostoUnitario.setToolTipText("");
        jPanel1.add(txtCostoUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 80, -1));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("% :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, -1, 20));

        txtPorcentaje.setEditable(false);
        txtPorcentaje.setBackground(new java.awt.Color(255, 255, 0));
        txtPorcentaje.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPorcentaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPorcentaje.setText("30");
        jPanel1.add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 50, -1));

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 255, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Precio Venta:");
        jLabel17.setToolTipText("");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, 140, 20));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBackground(new java.awt.Color(102, 255, 102));
        txtPrecioVenta.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 250, 80, -1));

        TablaUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePrincipal.setViewportView(TablaUnidad);

        jPanel1.add(jScrollPanePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 420, 1300, 220));

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Buscar:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, -1, -1));

        txtBuscarProductoEnTABLA.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoEnTABLA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProductoEnTABLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 380, 70, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, -1));

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Rojo.png"))); // NOI18N
        jLabel19.setText("Stock critico");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Amarrilo.png"))); // NOI18N
        jLabel20.setText("Stock Medio");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-verde.png"))); // NOI18N
        jLabel21.setText("Stock Estable");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, -1, 30));

        btbModificar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbModificar.setText("Modificar");
        jPanel1.add(btbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 670, 150, 40));

        btbInofrmacionLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbInofrmacionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veer Lote.png"))); // NOI18N
        btbInofrmacionLote.setText("Información de Lote");
        jPanel1.add(btbInofrmacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 670, 240, 30));

        btbRegistrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrar.setText("Registrar");
        jPanel1.add(btbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 667, 140, 40));

        btbHistorialMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbHistorialMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbHistorialMovimiento.setText("Historial de Movimiento");
        btbHistorialMovimiento.addActionListener(this::btbHistorialMovimientoActionPerformed);
        jPanel1.add(btbHistorialMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, -1, -1));

        btbOcultarHistorial.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbOcultarHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbOcultarHistorial.setText("Ocultar Historial");
        btbOcultarHistorial.setToolTipText("");
        jPanel1.add(btbOcultarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 240, -1));

        TablaHistorialMovimienrto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneHistorialMovimiento.setViewportView(TablaHistorialMovimienrto);

        jPanel1.add(jScrollPaneHistorialMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 420, 1300, 220));

        txtBuscarHistorial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarHistorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 380, 70, -1));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbConfirmarActualizacion.setText("  Confirmar Modificación");
        btbConfirmarActualizacion.addActionListener(this::btbConfirmarActualizacionActionPerformed);
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 270, 30));

        btbCancelarModificaion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarModificaion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarModificaion.setText("Cancelar ");
        jPanel1.add(btbCancelarModificaion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, 210, 30));

        TablaLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneInformacionLote.setViewportView(TablaLote);

        jPanel1.add(jScrollPaneInformacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 420, 1300, 220));

        btbOcultarLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbOcultarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbOcultarLote.setText("Ocultar Lote");
        jPanel1.add(btbOcultarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 673, 210, 30));

        txtBuscarLote.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 380, 70, -1));

        btbModificarLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbModificarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbModificarLote.setText("Modificar Lote");
        btbModificarLote.addActionListener(this::btbModificarLoteActionPerformed);
        jPanel1.add(btbModificarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 240, 30));

        btbConfirmaModificacionLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmaModificacionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmaModificacionLote.setText("Confirmar Modificación");
        btbConfirmaModificacionLote.addActionListener(this::btbConfirmaModificacionLoteActionPerformed);
        jPanel1.add(btbConfirmaModificacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 670, 260, 30));

        btbCancelarModificacionLote.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarModificacionLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarModificacionLote.setText("Cancelar");
        jPanel1.add(btbCancelarModificacionLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 673, 210, 30));

        lblValidaProductoUnidad.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidaProductoUnidad.setForeground(new java.awt.Color(255, 0, 0));
        lblValidaProductoUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidaProductoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 390, 20));

        lblValidarProveedorUnida.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarProveedorUnida.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarProveedorUnida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidarProveedorUnida.setToolTipText("");
        jPanel1.add(lblValidarProveedorUnida, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 220, 20));

        lblValidarAlamcenUnidad.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarAlamcenUnidad.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarAlamcenUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarAlamcenUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 150, 440, 20));

        lblValidarCantidaUnidad.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarCantidaUnidad.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarCantidaUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarCantidaUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 220, 140, 20));

        lblValidarStockMaximoUnida.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarStockMaximoUnida.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarStockMaximoUnida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarStockMaximoUnida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 130, 20));

        lblValidarStockMinimo.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarStockMinimo.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarStockMinimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 120, 20));

        lblValidarPorcentaje.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarPorcentaje.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, 100, 20));

        lblValidarCostoUnitario.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarCostoUnitario.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarCostoUnitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarCostoUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 120, 20));

        lblValidarPrecioVenta.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblValidarPrecioVenta.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarPrecioVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1193, 280, 160, 20));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1380, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1376, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbHistorialMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbHistorialMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbHistorialMovimientoActionPerformed

    private void btbConfirmarActualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConfirmarActualizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbConfirmarActualizacionActionPerformed

    private void btbModificarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbModificarLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbModificarLoteActionPerformed

    private void btbConfirmaModificacionLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConfirmaModificacionLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbConfirmaModificacionLoteActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JTable TablaHistorialMovimienrto;
    public static javax.swing.JTable TablaLote;
    public static javax.swing.JTable TablaUnidad;
    public static javax.swing.JButton btbCancelarModificacionLote;
    public static javax.swing.JButton btbCancelarModificaion;
    public static javax.swing.JButton btbConfirmaModificacionLote;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbHistorialMovimiento;
    public static javax.swing.JButton btbInofrmacionLote;
    public static javax.swing.JButton btbModificar;
    public static javax.swing.JButton btbModificarLote;
    public static javax.swing.JButton btbOcultarHistorial;
    public static javax.swing.JButton btbOcultarLote;
    public static javax.swing.JButton btbRegistrar;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuantDebitar;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaAcreditar;
    public static javax.swing.JComboBox<Proveedor> jComboBoxProveedor;
    public static javax.swing.JComboBox<Almacen> jComboBoxUbicacion;
    public static javax.swing.JComboBox<Producto> jComboProductoUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPaneHistorialMovimiento;
    public static javax.swing.JScrollPane jScrollPaneInformacionLote;
    public static javax.swing.JScrollPane jScrollPanePrincipal;
    public static javax.swing.JLabel lblValidaProductoUnidad;
    public static javax.swing.JLabel lblValidarAlamcenUnidad;
    public static javax.swing.JLabel lblValidarCantidaUnidad;
    public static javax.swing.JLabel lblValidarCostoUnitario;
    public static javax.swing.JLabel lblValidarPorcentaje;
    public static javax.swing.JLabel lblValidarPrecioVenta;
    public static javax.swing.JLabel lblValidarProveedorUnida;
    public static javax.swing.JLabel lblValidarStockMaximoUnida;
    public static javax.swing.JLabel lblValidarStockMinimo;
    public static javax.swing.JTextField txtBuscarHistorial;
    public static javax.swing.JTextField txtBuscarLote;
    public static javax.swing.JTextField txtBuscarProductoCombox;
    public static javax.swing.JTextField txtBuscarProductoEnTABLA;
    public static javax.swing.JTextField txtBuscarProveedor;
    public static javax.swing.JTextField txtBuscarUbicacion;
    public static javax.swing.JTextField txtCantidadProducto;
    public static javax.swing.JTextField txtCostoUnitario;
    public static javax.swing.JTextField txtPorcentaje;
    public static javax.swing.JTextField txtPrecioVenta;
    public static javax.swing.JTextField txtStockMaximo;
    public static javax.swing.JTextField txtStockMinimo;
    public static javax.swing.JTextField txtTipoProductoUnidad;
    // End of variables declaration//GEN-END:variables
}
