/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Gestionar_Proveedor;


import ModeloDAO.ProveedorDao;
import Validacion.Validar_Proveedor;

import dictionary.AutoCorrectorGlobal;
import java.sql.SQLException;

/**
 *
 * @author Adrian
 */
public class Gestionar_Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Gestionar_Proveedor
     */
    public Gestionar_Proveedor() throws ClassNotFoundException, SQLException {
        initComponents();
        
        setTitle("Gestionar Proveedor");
            
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        p.MostrarListaDeProveedor();
        p.centrarTextoTabla(TablaProveedor);
        p.configurarCampoTelefono();
       p.agregarFiltroBusqueda();
        txtBuscar.putClientProperty("autocorrect", false);
      txtRFCProveedor.putClientProperty("autocorrect", false);
        AutoCorrectorGlobal.aplicar(this);
       txtID.setVisible(false);
       btbCancelarProveedor.setVisible(false);
       btbConfirmarActualizacion.setVisible(false);
        btbCancelarProductoSuministrado.setVisible(false);
        
      validar_Proveedor.inicializarValidacionesProveedor();
       
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtDireccionProveedor = new javax.swing.JTextField();
        txtEmailProveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRFCProveedor = new javax.swing.JTextField();
        btbRegistrarProveedor = new javax.swing.JButton();
        btbVolverProveedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedor = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btbEliminarProveedor = new javax.swing.JButton();
        btbActualizarProveedor = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarProveedor = new javax.swing.JButton();
        btbProductoDEProveedor = new javax.swing.JButton();
        btbCancelarProductoSuministrado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductoProveedore = new javax.swing.JTable();
        lblNompreProveedorValidacion = new javax.swing.JLabel();
        lblNumeroTelefonoValidacion = new javax.swing.JLabel();
        lblEmailValidacion = new javax.swing.JLabel();
        lblRfcValidadcion = new javax.swing.JLabel();
        lblDirrecionValidacion = new javax.swing.JLabel();
        ComboBoxOperadora = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lblMensajeOperadora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 350, 10));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de Inventario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, 40));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestionar Proveedor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        txtNombreProveedor.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtNombreProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, -1, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 50));

        txtTelefonoProveedor.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtTelefonoProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 180, 30));

        txtDireccionProveedor.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtDireccionProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 190, -1));

        txtEmailProveedor.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtEmailProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEmailProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 220, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("email :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RIF:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, 30));

        txtRFCProveedor.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtRFCProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRFCProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 220, 30));

        btbRegistrarProveedor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrarProveedor.setText("  Registrar");
        btbRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRegistrarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btbRegistrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 670, 160, 30));

        btbVolverProveedor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Atras.png"))); // NOI18N
        btbVolverProveedor.setText(" Volver");
        btbVolverProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVolverProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btbVolverProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 130, -1));

        TablaProveedor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProveedor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 1260, 340));

        txtBuscar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 110, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, -1, 30));

        btbEliminarProveedor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbEliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btbEliminarProveedor.setText("   Eliminar");
        btbEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEliminarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btbEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, 150, 30));

        btbActualizarProveedor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbActualizarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbActualizarProveedor.setText("  Actualizar");
        btbActualizarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbActualizarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btbActualizarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 170, 30));

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, -1));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacion.setText(" Confirmar Actualizacion");
        btbConfirmarActualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbConfirmarActualizacionActionPerformed(evt);
            }
        });
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, -1, 30));

        btbCancelarProveedor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarProveedor.setText("Cancelar");
        btbCancelarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btbCancelarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 670, 150, 30));

        btbProductoDEProveedor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbProductoDEProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Producto Pequeno.png"))); // NOI18N
        btbProductoDEProveedor.setText(" Ver Producto Suministrado");
        btbProductoDEProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbProductoDEProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btbProductoDEProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, -1, -1));

        btbCancelarProductoSuministrado.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarProductoSuministrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarProductoSuministrado.setText("Cancelar");
        btbCancelarProductoSuministrado.setToolTipText("");
        btbCancelarProductoSuministrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelarProductoSuministradoActionPerformed(evt);
            }
        });
        jPanel1.add(btbCancelarProductoSuministrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 160, 30));

        TablaProductoProveedore.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaProductoProveedore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaProductoProveedore);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 1120, 330));

        lblNompreProveedorValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNompreProveedorValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNompreProveedorValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNompreProveedorValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 230, 20));

        lblNumeroTelefonoValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNumeroTelefonoValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNumeroTelefonoValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNumeroTelefonoValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 210, 20));

        lblEmailValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblEmailValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblEmailValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblEmailValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 280, 20));

        lblRfcValidadcion.setBackground(new java.awt.Color(0, 0, 0));
        lblRfcValidadcion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblRfcValidadcion.setForeground(new java.awt.Color(253, 253, 2));
        lblRfcValidadcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblRfcValidadcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 410, 20));

        lblDirrecionValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblDirrecionValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblDirrecionValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDirrecionValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 220, 20));

        ComboBoxOperadora.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ComboBoxOperadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Operadora", "Movistar (0414) ", "Movistar (0424)", "Digitel (0412)", "Digitel (0422)", "Movilnet (0416) ", "Movilnet (0426)" }));
        jPanel1.add(ComboBoxOperadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Operadora :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        lblMensajeOperadora.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblMensajeOperadora.setForeground(new java.awt.Color(255, 0, 0));
        lblMensajeOperadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblMensajeOperadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 260, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Componentes automotrices.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, -1, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1375, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbVolverProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVolverProveedorActionPerformed

    }//GEN-LAST:event_btbVolverProveedorActionPerformed

    private void btbRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRegistrarProveedorActionPerformed
      
    }//GEN-LAST:event_btbRegistrarProveedorActionPerformed

    private void txtDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionProveedorActionPerformed

    }//GEN-LAST:event_txtDireccionProveedorActionPerformed

    private void btbActualizarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbActualizarProveedorActionPerformed

    }//GEN-LAST:event_btbActualizarProveedorActionPerformed

    private void btbCancelarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarProveedorActionPerformed

    }//GEN-LAST:event_btbCancelarProveedorActionPerformed

    private void btbConfirmarActualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConfirmarActualizacionActionPerformed

    }//GEN-LAST:event_btbConfirmarActualizacionActionPerformed

    private void btbEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEliminarProveedorActionPerformed

    }//GEN-LAST:event_btbEliminarProveedorActionPerformed

    private void btbProductoDEProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbProductoDEProveedorActionPerformed

    }//GEN-LAST:event_btbProductoDEProveedorActionPerformed

    private void btbCancelarProductoSuministradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarProductoSuministradoActionPerformed
 


       
    }//GEN-LAST:event_btbCancelarProductoSuministradoActionPerformed

    /**
     * @param args the command line arguments
     * 
     * 
     */
    
    Validacion.Validar_Proveedor validar_Proveedor = new Validar_Proveedor();
   
    ModeloDAO.ProveedorDao p = new  ProveedorDao();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ComboBoxOperadora;
    public static javax.swing.JTable TablaProductoProveedore;
    public static javax.swing.JTable TablaProveedor;
    public static javax.swing.JButton btbActualizarProveedor;
    public static javax.swing.JButton btbCancelarProductoSuministrado;
    public static javax.swing.JButton btbCancelarProveedor;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbEliminarProveedor;
    public static javax.swing.JButton btbProductoDEProveedor;
    public static javax.swing.JButton btbRegistrarProveedor;
    public static javax.swing.JButton btbVolverProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblDirrecionValidacion;
    public static javax.swing.JLabel lblEmailValidacion;
    public static javax.swing.JLabel lblMensajeOperadora;
    public static javax.swing.JLabel lblNompreProveedorValidacion;
    public static javax.swing.JLabel lblNumeroTelefonoValidacion;
    public static javax.swing.JLabel lblRfcValidadcion;
    public static javax.swing.JTextField txtBuscar;
    public static javax.swing.JTextField txtDireccionProveedor;
    public static javax.swing.JTextField txtEmailProveedor;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtNombreProveedor;
    public static javax.swing.JTextField txtRFCProveedor;
    public static javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
