/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Almacen;

import Modelo.Inventario;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class Ajuste_Unidad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ajuste_Unidad.class.getName());

    /**
     * Creates new form Ajuste_Unidad
     */
    public Ajuste_Unidad() {
        initComponents();
        setTitle("Ajuste Unidad");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAccionAjuste = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoProductuUnidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxProductoUnidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        btbVolverMenu = new javax.swing.JButton();
        btbRealizarMovimiento = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInformacionProducto = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCuentas = new javax.swing.JComboBox<>();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajuste Unidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acción :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtAccionAjuste.setEditable(false);
        txtAccionAjuste.setBackground(new java.awt.Color(255, 153, 153));
        txtAccionAjuste.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtAccionAjuste.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccionAjuste.setText("AJUSTE");
        jPanel1.add(txtAccionAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 100, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo Producto :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtTipoProductuUnidad.setEditable(false);
        txtTipoProductuUnidad.setBackground(new java.awt.Color(51, 102, 255));
        txtTipoProductuUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTipoProductuUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProductuUnidad.setText("UNIDAD");
        jPanel1.add(txtTipoProductuUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 100, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Producto :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jComboBoxProductoUnidad.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(jComboBoxProductoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 570, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        txtBuscarProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 80, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setToolTipText("");
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 170, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Detalle :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        txtDetalle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jPanel1.add(txtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 530, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 640, 130, 40));

        btbRealizarMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRealizarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbRealizarMovimiento.setText("Realizar Movimiento");
        jPanel1.add(btbRealizarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 240, 40));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Información Completa del Producto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 131, -1, 30));

        jTextAreaInformacionProducto.setEditable(false);
        jTextAreaInformacionProducto.setColumns(20);
        jTextAreaInformacionProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jTextAreaInformacionProducto.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInformacionProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 166, 430, 320));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cuenta Pasivo :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, -1, -1));

        jComboBoxCuentas.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jPanel1.add(jComboBoxCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 280, -1));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1440, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1433, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel FondoPantalla;
    public static javax.swing.JButton btbRealizarMovimiento;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentas;
    public static javax.swing.JComboBox<Inventario> jComboBoxProductoUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAreaInformacionProducto;
    public static javax.swing.JTextField txtAccionAjuste;
    public static javax.swing.JTextField txtBuscarProducto;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtDetalle;
    public static javax.swing.JTextField txtTipoProductuUnidad;
    // End of variables declaration//GEN-END:variables
}
