/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Almacen;

import Modelo.Inventario;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class Ajuste_Solido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ajuste_Solido.class.getName());

    /**
     * Creates new form Ajuste_Solido
     */
    public Ajuste_Solido() {
        initComponents();
        setTitle("Ajuste Solido");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAccionAjuste = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoProductoSolido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDetalleUnidad = new javax.swing.JTextField();
        btbVolverMenu = new javax.swing.JButton();
        btbRealizarMovimiento = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaInformacionProducto = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCuentaPasivo = new javax.swing.JComboBox<>();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajuste Solido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acción :");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtAccionAjuste.setEditable(false);
        txtAccionAjuste.setBackground(new java.awt.Color(255, 153, 153));
        txtAccionAjuste.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtAccionAjuste.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccionAjuste.setText("AJUSTE");
        jPanel1.add(txtAccionAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo Producto :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        txtTipoProductoSolido.setEditable(false);
        txtTipoProductoSolido.setBackground(new java.awt.Color(255, 153, 51));
        txtTipoProductoSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTipoProductoSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProductoSolido.setText("SOLIDO");
        jPanel1.add(txtTipoProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Producto :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jComboBoxProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(jComboBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 530, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar :");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        txtBuscarProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 70, -1));

        txtCantidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setToolTipText("");
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 180, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Detalle :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        txtDetalleUnidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtDetalleUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDetalleUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 530, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 643, 140, 40));

        btbRealizarMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRealizarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbRealizarMovimiento.setText("Realizar Movimiento");
        jPanel1.add(btbRealizarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 642, 230, 40));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Información Completa del Producto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        TxtAreaInformacionProducto.setEditable(false);
        TxtAreaInformacionProducto.setColumns(20);
        TxtAreaInformacionProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        TxtAreaInformacionProducto.setRows(5);
        jScrollPane1.setViewportView(TxtAreaInformacionProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 176, 450, 320));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cuenta Pasivo :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 570, -1, -1));

        jComboBoxCuentaPasivo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(jComboBoxCuentaPasivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 310, -1));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1410, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1408, 744));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel FondoPantalla;
    public static javax.swing.JTextArea TxtAreaInformacionProducto;
    public static javax.swing.JButton btbRealizarMovimiento;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaPasivo;
    public static javax.swing.JComboBox<Inventario> jComboBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtAccionAjuste;
    public static javax.swing.JTextField txtBuscarProducto;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtDetalleUnidad;
    public static javax.swing.JTextField txtTipoProductoSolido;
    // End of variables declaration//GEN-END:variables
}
