/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Almacen;

import Modelo.Inventario;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class Ajuste_Liquido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ajuste_Liquido.class.getName());

    /**
     * Creates new form Ajuste_Liquido
     */
    public Ajuste_Liquido() {
        initComponents();
        setTitle("Ajuste Liquiod");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAccionAjuste = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTipoProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxProductoLiquidoAjuste = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInformacionLiquidoAjuste = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCuentaInventario = new javax.swing.JComboBox<>();
        btbVolveAlMenu = new javax.swing.JButton();
        btbRealizarMovimiento = new javax.swing.JButton();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajuste Liquido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        txtAccionAjuste.setEditable(false);
        txtAccionAjuste.setBackground(new java.awt.Color(255, 153, 153));
        txtAccionAjuste.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtAccionAjuste.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccionAjuste.setText("AJUSTE");
        jPanel1.add(txtAccionAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 100, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Producto :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtTipoProducto.setEditable(false);
        txtTipoProducto.setBackground(new java.awt.Color(255, 255, 51));
        txtTipoProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTipoProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProducto.setText("LIQUIDO");
        jPanel1.add(txtTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 100, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jComboBoxProductoLiquidoAjuste.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jPanel1.add(jComboBoxProductoLiquidoAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 570, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        txtBuscarProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 80, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 190, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Detalle :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        txtDetalle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtDetalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 540, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Información Completa del Producto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 350, -1));

        jTextAreaInformacionLiquidoAjuste.setEditable(false);
        jTextAreaInformacionLiquidoAjuste.setColumns(20);
        jTextAreaInformacionLiquidoAjuste.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jTextAreaInformacionLiquidoAjuste.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInformacionLiquidoAjuste);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 440, 340));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cuenta Pasivo :");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, -1, -1));

        jComboBoxCuentaInventario.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(jComboBoxCuentaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 570, 300, -1));

        btbVolveAlMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolveAlMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolveAlMenu.setText("Volver");
        jPanel1.add(btbVolveAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, 40));

        btbRealizarMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRealizarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbRealizarMovimiento.setText("Realizar Movimiento");
        jPanel1.add(btbRealizarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 250, 40));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 742));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel FondoPantalla;
    public static javax.swing.JButton btbRealizarMovimiento;
    public static javax.swing.JButton btbVolveAlMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaInventario;
    public static javax.swing.JComboBox<Inventario> jComboBoxProductoLiquidoAjuste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAreaInformacionLiquidoAjuste;
    public static javax.swing.JTextField txtAccionAjuste;
    public static javax.swing.JTextField txtBuscarProducto;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtDetalle;
    public static javax.swing.JTextField txtTipoProducto;
    // End of variables declaration//GEN-END:variables
}
