/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Almacen;


import Funciones.BCV;
import ModeloDAO.AlmacenDao;
import Validacion.Validar_Almacen;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Modelo.Inventario;
import Modelo.cuenta;
import ModeloDAO.CuentaDao;
import ModeloDAO.InventarioUnidadDAO;
import ModeloDAO.InventarioLiquidoDao;
import ModeloDAO.MovientosDao;
import Validacion.ValidaR_Ajuste_Solido;
import Validacion.Validar_Ajuste_Liquido;
import Validacion.Validar_Ajuste_Unidad;
import Validacion.Validar_SALIDA_Unidad;
import Validacion.Validar_Salida_Liquido;
import Validacion.Validar_Salida_Solido;
import Vista_Usuari_Empleado.Menu_Sistema;
import controladorLogin.ControladorLogin;
import dictionary.AutoCorrectorGlobal;

/**
 *
 * @author Adrian
 */
public class Gestionar_Almacenn extends javax.swing.JFrame {

    /**
     * Creates new form Gestionar_Almacen
     */
    public Gestionar_Almacenn() throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle("Gestionar Almacén");
      
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        almacenDao.MostrarAlmacen();
  
       lblTotalEnBolivares.setVisible(false);
    txtTotalEnBolivares.setVisible(false);
    lblTotalEnDolares.setVisible(false);
    txtTotalEnDolares.setVisible(false);
       lblTasaDelDolar.setVisible(false);
       txtDolarHoy.setVisible(false);

       
    txtCantidadAjusteSolido.putClientProperty("autocorrect", false);
         AutoCorrectorGlobal.aplicar(this);
       
        JComboxSUnidad.setVisible(false);
        btbRealizarSalidaUnidad.setVisible(false);
        txtTIPOUNIDAD.setVisible(false);
        btbConfirmarActualizacion.setVisible(false);
        btbCancelarActualizacion.setVisible(false);
        txtIDAlmacen.setVisible(false);
     
     // inventarioLiquidoDao.CargarComboxBoxLiquido();
      btbRealizarAjusteUnidad.setVisible(false);
    

     
     lblAccion.setVisible(false);
     txtSALIDA.setVisible(false);
     
     
     
     lblTIPOPRODUCTO.setVisible(false);
     txtTIPOLIQUIDO.setVisible(false);
     
     lblProducto.setVisible(false);
     JComboxSOLIDO.setVisible(false);
     
     lblCantidad.setVisible(false);
     txtCantidadLiquido.setVisible(false);
     
     lblDatelle.setVisible(false);
     txtDatelleLiquido.setVisible(false);

     
     lblPrecioVenta.setVisible(false);
     txtPrecioVentaLiquido.setVisible(false);
     
     btbREALIZARSALIDASOLIDO.setVisible(false);
     
     txtAjuste.setVisible(false);
     
     btbRealizarAjuste.setVisible(false);
     
     txtTIPOLIQUIDOOOOOO.setVisible(false);
     
     btbREALIZARSALIDALIQUIDOoooo.setVisible(false);
     JComboxLiquido.setVisible(false);
    
     
     
   
     
     btbRealizarAjusteLiquido.setVisible(false);
     
     Vali.inicializarValidacionesAlmacen();
     
     almacenDao.agregarFiltroBusqueda();
     
     Cu.cargarComboSalidaYAjuste();
     Cu.CargarCuentaIngreso();
     Cu.CargarCuentaInventario();
     lblCuentas.setVisible(false);
     lblcuentaIngreso.setVisible(false);
     jComboBoxCuentas.setVisible(false);
     jComboBoxCuentasIngreso.setVisible(false);
     jComboBoxCuentasInventario.setVisible(false);
     SlVALI.inicializarValidacionesSalidaLiquido();
     txtCantidadUnidad.setVisible(false);
     txtDatelleUnidad.setVisible(false);
     txtPrecioVentaUnidad.setVisible(false);
   slUnida.inicializarValidacionesSalidaUnidad();
   txtCantidadSolido.setVisible(false);
   txtDatelleSolido.setVisible(false);
   txtPrecioVentaSOLIDONuevo.setVisible(false);
   SlSolido.inicializarValidacionesSalidaSolido();
   txtCantidadAjusteSolido.setVisible(false);
   txtDatelleAjsuteSolido.setVisible(false);
   AjsuteSolido.inicializarValidacionesAjusteSolido();
   txtDatelleAjsuteUNIDAD.setVisible(false);
   txtCantidadAjusteUNIDAD.setVisible(false);
   AjusteUnidad.inicializarValidacionesAjusteUnidad();
   txtCantidadAjusteLIQUIDO.setVisible(false);
   txtDatelleAjsuteLIQUIDO.setVisible(false);
   
   AjusteLiquido.inicializarValidacionesAjusteLiquido();
    iv.CargarComboxBoxUnidad();
      
       

       ct.CalcularTotal();
       
       ct.CalcularTotalSolido();
       ct.CalcularTotalUnidad();
      bcv.mostrarTasaEnCampo(txtDolarHoy);
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCantidadAjusteLIQUIDO = new javax.swing.JTextField();
        lblValidarCantidadAJUSTELIQUIDO = new javax.swing.JLabel();
        lblValidadarComboxLIQUIDOAJUSTE1 = new javax.swing.JLabel();
        JComboxLiquido = new javax.swing.JComboBox<>();
        lblValidarDetalleAjusteLIQUIDO = new javax.swing.JLabel();
        txtDatelleAjsuteLIQUIDO = new javax.swing.JTextField();
        txtDatelleAjsuteUNIDAD = new javax.swing.JTextField();
        lblValidarDetalleAjusteUNIDAD = new javax.swing.JLabel();
        txtCantidadAjusteUNIDAD = new javax.swing.JTextField();
        lblValidadarComboxUNIDADAJUSTE = new javax.swing.JLabel();
        lblValidarCantidadAJUSTEUNIDAD = new javax.swing.JLabel();
        JComboxSUnidad = new javax.swing.JComboBox<>();
        lblValidarCantidadSolido1 = new javax.swing.JLabel();
        lblValidadarComboxSolidoAjuste = new javax.swing.JLabel();
        txtCantidadAjusteSolido = new javax.swing.JTextField();
        lblValidarDetalleAjusteSolido = new javax.swing.JLabel();
        txtDatelleAjsuteSolido = new javax.swing.JTextField();
        JComboxSOLIDO = new javax.swing.JComboBox<>();
        lblValidarDetalleSOLIDO = new javax.swing.JLabel();
        lblValidacionPrecioVentaSolido = new javax.swing.JLabel();
        txtPrecioVentaSOLIDONuevo = new javax.swing.JTextField();
        txtCantidadSolido = new javax.swing.JTextField();
        txtDatelleSolido = new javax.swing.JTextField();
        lblValidarCantidadSolido = new javax.swing.JLabel();
        lblValidadarComboxSolido = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblDatelle = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblPrecioVenta = new javax.swing.JLabel();
        lblValidacionPrecioVentaUnidad = new javax.swing.JLabel();
        lblValidarDetalleUnidad = new javax.swing.JLabel();
        txtPrecioVentaUnidad = new javax.swing.JTextField();
        lblValidadarComboxUnidad = new javax.swing.JLabel();
        txtDatelleUnidad = new javax.swing.JTextField();
        btbRealizarSalidaUnidad = new javax.swing.JButton();
        lblValidarCantidadAjusteSolido = new javax.swing.JLabel();
        txtCantidadUnidad = new javax.swing.JTextField();
        btbREALIZARSALIDALIQUIDOoooo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblValidarDetalleLiquyido = new javax.swing.JLabel();
        lblValidarCantidadLiquido = new javax.swing.JLabel();
        txtDatelleLiquido = new javax.swing.JTextField();
        lblValidadarComboxLiquido = new javax.swing.JLabel();
        txtPrecioVentaLiquido = new javax.swing.JTextField();
        txtCantidadLiquido = new javax.swing.JTextField();
        lblValidacionPrecioVentaLiquido = new javax.swing.JLabel();
        lblEstanteValidacion = new javax.swing.JLabel();
        lblCapacidadValidacion = new javax.swing.JLabel();
        lblNivelValidacion = new javax.swing.JLabel();
        lblPasilloValidacion = new javax.swing.JLabel();
        txtPasillolmacen = new javax.swing.JTextField();
        btbRegistrarAlmacen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblPasillo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btbVolverMenu = new javax.swing.JButton();
        lblAlaValidacion = new javax.swing.JLabel();
        lblALA = new javax.swing.JLabel();
        ComboxAla = new javax.swing.JComboBox<>();
        lblNivel = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        btbEliminarAlmacen = new javax.swing.JButton();
        btbActualizarALmacen = new javax.swing.JButton();
        txtIDAlmacen = new javax.swing.JTextField();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarActualizacion = new javax.swing.JButton();
        lblAccion = new javax.swing.JLabel();
        txtSALIDA = new javax.swing.JTextField();
        lblTIPOPRODUCTO = new javax.swing.JLabel();
        txtTIPOLIQUIDO = new javax.swing.JTextField();
        btbREALIZARSALIDASOLIDO = new javax.swing.JButton();
        txtAjuste = new javax.swing.JTextField();
        txtTIPOUNIDAD = new javax.swing.JTextField();
        txtTIPOLIQUIDOOOOOO = new javax.swing.JTextField();
        lblCuentas = new javax.swing.JLabel();
        jComboBoxCuentas = new javax.swing.JComboBox<>();
        lblcuentaIngreso = new javax.swing.JLabel();
        jComboBoxCuentasIngreso = new javax.swing.JComboBox<>();
        jComboBoxCuentasInventario = new javax.swing.JComboBox<>();
        txtDolarHoy = new javax.swing.JTextField();
        lblTasaDelDolar = new javax.swing.JLabel();
        lblTotalEnBolivares = new javax.swing.JLabel();
        txtTotalEnBolivares = new javax.swing.JTextField();
        lblTotalEnDolares = new javax.swing.JLabel();
        txtTotalEnDolares = new javax.swing.JTextField();
        lblBuscarAlmacen = new javax.swing.JLabel();
        txtEstanteAlmacen = new javax.swing.JTextField();
        lblCaoacidad = new javax.swing.JLabel();
        txtBuscarAlmacen = new javax.swing.JTextField();
        btbRealizarAjuste = new javax.swing.JButton();
        txtCapacidadAlmacen = new javax.swing.JTextField();
        btbRealizarAjusteUnidad = new javax.swing.JButton();
        lblEstante = new javax.swing.JLabel();
        btbRealizarAjusteLiquido = new javax.swing.JButton();
        jScrollPaneAlmacen = new javax.swing.JScrollPane();
        TablaAlmacen = new javax.swing.JTable();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCantidadAjusteLIQUIDO.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtCantidadAjusteLIQUIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 30));

        lblValidarCantidadAJUSTELIQUIDO.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarCantidadAJUSTELIQUIDO.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarCantidadAJUSTELIQUIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 270, 20));

        lblValidadarComboxLIQUIDOAJUSTE1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidadarComboxLIQUIDOAJUSTE1.setForeground(new java.awt.Color(255, 0, 0));
        lblValidadarComboxLIQUIDOAJUSTE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidadarComboxLIQUIDOAJUSTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 570, 20));

        JComboxLiquido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(JComboxLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 112, 580, 30));

        lblValidarDetalleAjusteLIQUIDO.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarDetalleAjusteLIQUIDO.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarDetalleAjusteLIQUIDO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarDetalleAjusteLIQUIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 270, 20));

        txtDatelleAjsuteLIQUIDO.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtDatelleAjsuteLIQUIDO.setToolTipText("");
        jPanel1.add(txtDatelleAjsuteLIQUIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 402, 270, 30));

        txtDatelleAjsuteUNIDAD.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtDatelleAjsuteUNIDAD.setToolTipText("");
        jPanel1.add(txtDatelleAjsuteUNIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 402, 270, 30));

        lblValidarDetalleAjusteUNIDAD.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarDetalleAjusteUNIDAD.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarDetalleAjusteUNIDAD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarDetalleAjusteUNIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 270, 20));

        txtCantidadAjusteUNIDAD.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtCantidadAjusteUNIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 30));

        lblValidadarComboxUNIDADAJUSTE.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidadarComboxUNIDADAJUSTE.setForeground(new java.awt.Color(255, 0, 0));
        lblValidadarComboxUNIDADAJUSTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidadarComboxUNIDADAJUSTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 570, 20));

        lblValidarCantidadAJUSTEUNIDAD.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarCantidadAJUSTEUNIDAD.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarCantidadAJUSTEUNIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 270, 20));

        JComboxSUnidad.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(JComboxSUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 112, 580, 30));

        lblValidarCantidadSolido1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarCantidadSolido1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarCantidadSolido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 270, 20));

        lblValidadarComboxSolidoAjuste.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidadarComboxSolidoAjuste.setForeground(new java.awt.Color(255, 0, 0));
        lblValidadarComboxSolidoAjuste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidadarComboxSolidoAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 570, 20));

        txtCantidadAjusteSolido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtCantidadAjusteSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 30));

        lblValidarDetalleAjusteSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarDetalleAjusteSolido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarDetalleAjusteSolido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarDetalleAjusteSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 270, 20));

        txtDatelleAjsuteSolido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtDatelleAjsuteSolido.setToolTipText("");
        jPanel1.add(txtDatelleAjsuteSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 402, 270, 30));

        JComboxSOLIDO.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(JComboxSOLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 112, 580, 30));

        lblValidarDetalleSOLIDO.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarDetalleSOLIDO.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarDetalleSOLIDO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarDetalleSOLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 270, 20));

        lblValidacionPrecioVentaSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidacionPrecioVentaSolido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidacionPrecioVentaSolido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidacionPrecioVentaSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 230, 20));

        txtPrecioVentaSOLIDONuevo.setEditable(false);
        txtPrecioVentaSOLIDONuevo.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtPrecioVentaSOLIDONuevo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVentaSOLIDONuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 170, -1));

        txtCantidadSolido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtCantidadSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 30));

        txtDatelleSolido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtDatelleSolido.setToolTipText("");
        jPanel1.add(txtDatelleSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 402, 270, 30));

        lblValidarCantidadSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarCantidadSolido.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarCantidadSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 270, 20));

        lblValidadarComboxSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidadarComboxSolido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidadarComboxSolido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidadarComboxSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 570, 20));

        lblCantidad.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("CANTIDAD:");
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        lblDatelle.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblDatelle.setForeground(new java.awt.Color(255, 255, 255));
        lblDatelle.setText("Datelle :");
        jPanel1.add(lblDatelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        lblProducto.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setText("Producto :");
        lblProducto.setToolTipText("");
        jPanel1.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        lblPrecioVenta.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblPrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioVenta.setText("Precio de Venta :");
        jPanel1.add(lblPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        lblValidacionPrecioVentaUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidacionPrecioVentaUnidad.setForeground(new java.awt.Color(255, 0, 0));
        lblValidacionPrecioVentaUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidacionPrecioVentaUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 230, 20));

        lblValidarDetalleUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarDetalleUnidad.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarDetalleUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarDetalleUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 270, 20));

        txtPrecioVentaUnidad.setEditable(false);
        txtPrecioVentaUnidad.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtPrecioVentaUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVentaUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 170, -1));

        lblValidadarComboxUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidadarComboxUnidad.setForeground(new java.awt.Color(255, 0, 0));
        lblValidadarComboxUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidadarComboxUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 570, 20));

        txtDatelleUnidad.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtDatelleUnidad.setToolTipText("");
        jPanel1.add(txtDatelleUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 402, 270, 30));

        btbRealizarSalidaUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRealizarSalidaUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/REALIZARSALIDA.png"))); // NOI18N
        btbRealizarSalidaUnidad.setText("Realizar Movimiento");
        btbRealizarSalidaUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRealizarSalidaUnidadActionPerformed(evt);
            }
        });
        jPanel1.add(btbRealizarSalidaUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 260, 50));

        lblValidarCantidadAjusteSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarCantidadAjusteSolido.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarCantidadAjusteSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 270, 20));

        txtCantidadUnidad.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtCantidadUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 30));

        btbREALIZARSALIDALIQUIDOoooo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbREALIZARSALIDALIQUIDOoooo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/REALIZARSALIDA.png"))); // NOI18N
        btbREALIZARSALIDALIQUIDOoooo.setText("Realizar Movimiento");
        btbREALIZARSALIDALIQUIDOoooo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbREALIZARSALIDALIQUIDOooooActionPerformed(evt);
            }
        });
        jPanel1.add(btbREALIZARSALIDALIQUIDOoooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 260, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 33, 340, 10));

        lblValidarDetalleLiquyido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarDetalleLiquyido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarDetalleLiquyido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarDetalleLiquyido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 270, 20));

        lblValidarCantidadLiquido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarCantidadLiquido.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarCantidadLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 270, 20));

        txtDatelleLiquido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtDatelleLiquido.setToolTipText("");
        jPanel1.add(txtDatelleLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 402, 270, 30));

        lblValidadarComboxLiquido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidadarComboxLiquido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidadarComboxLiquido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidadarComboxLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 570, 20));

        txtPrecioVentaLiquido.setEditable(false);
        txtPrecioVentaLiquido.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtPrecioVentaLiquido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVentaLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 170, -1));

        txtCantidadLiquido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtCantidadLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 30));

        lblValidacionPrecioVentaLiquido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidacionPrecioVentaLiquido.setForeground(new java.awt.Color(255, 0, 0));
        lblValidacionPrecioVentaLiquido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidacionPrecioVentaLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 230, 20));

        lblEstanteValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblEstanteValidacion.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblEstanteValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 140, 180, 20));

        lblCapacidadValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblCapacidadValidacion.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblCapacidadValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 244, 220, 20));

        lblNivelValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblNivelValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNivelValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNivelValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 110, 20));

        lblPasilloValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblPasilloValidacion.setForeground(new java.awt.Color(255, 0, 0));
        lblPasilloValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblPasilloValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, -1));

        txtPasillolmacen.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtPasillolmacen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPasillolmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, 30));

        btbRegistrarAlmacen.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrarAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrarAlmacen.setText(" Registrar");
        btbRegistrarAlmacen.setBorder(null);
        btbRegistrarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRegistrarAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btbRegistrarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 680, 120, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestionar Almacén");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        lblPasillo.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblPasillo.setForeground(new java.awt.Color(255, 255, 255));
        lblPasillo.setText("Pasillo :");
        jPanel1.add(lblPasillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de Inventario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 30));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        btbVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVolverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, -1, -1));

        lblAlaValidacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblAlaValidacion.setForeground(new java.awt.Color(255, 0, 51));
        lblAlaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblAlaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 170, 20));

        lblALA.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblALA.setForeground(new java.awt.Color(255, 255, 255));
        lblALA.setText("Ala :");
        jPanel1.add(lblALA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        ComboxAla.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        ComboxAla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IZQUIERDA", "DERECHA" }));
        jPanel1.add(ComboxAla, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        lblNivel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel.setText("Nivel :");
        jPanel1.add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        txtNivel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 80, -1));

        btbEliminarAlmacen.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbEliminarAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btbEliminarAlmacen.setText("Eliminar");
        btbEliminarAlmacen.setToolTipText("");
        btbEliminarAlmacen.setBorder(null);
        btbEliminarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEliminarAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btbEliminarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 110, 40));

        btbActualizarALmacen.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbActualizarALmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbActualizarALmacen.setText("Actualizar");
        btbActualizarALmacen.setBorder(null);
        btbActualizarALmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbActualizarALmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btbActualizarALmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, 130, 40));

        txtIDAlmacen.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtIDAlmacen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtIDAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, -1));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacion.setText("Confirmar Actualización");
        btbConfirmarActualizacion.setBorder(null);
        btbConfirmarActualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbConfirmarActualizacionActionPerformed(evt);
            }
        });
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, -1, 40));

        btbCancelarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActualizacion.setText("Cancelar");
        btbCancelarActualizacion.setToolTipText("");
        btbCancelarActualizacion.setBorder(null);
        btbCancelarActualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelarActualizacionActionPerformed(evt);
            }
        });
        jPanel1.add(btbCancelarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, 130, 40));

        lblAccion.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblAccion.setForeground(new java.awt.Color(255, 255, 255));
        lblAccion.setText("Acción:");
        jPanel1.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        txtSALIDA.setEditable(false);
        txtSALIDA.setBackground(new java.awt.Color(204, 255, 204));
        txtSALIDA.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtSALIDA.setText("SALIDA");
        jPanel1.add(txtSALIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        lblTIPOPRODUCTO.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTIPOPRODUCTO.setForeground(new java.awt.Color(255, 255, 255));
        lblTIPOPRODUCTO.setText("TIPO PRODUCTO: ");
        jPanel1.add(lblTIPOPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        txtTIPOLIQUIDO.setEditable(false);
        txtTIPOLIQUIDO.setBackground(new java.awt.Color(255, 255, 102));
        txtTIPOLIQUIDO.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTIPOLIQUIDO.setText("SOLIDO");
        jPanel1.add(txtTIPOLIQUIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        btbREALIZARSALIDASOLIDO.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbREALIZARSALIDASOLIDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/REALIZARSALIDA.png"))); // NOI18N
        btbREALIZARSALIDASOLIDO.setText("Realizar Movimiento");
        btbREALIZARSALIDASOLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbREALIZARSALIDASOLIDOActionPerformed(evt);
            }
        });
        jPanel1.add(btbREALIZARSALIDASOLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 260, 50));

        txtAjuste.setEditable(false);
        txtAjuste.setBackground(new java.awt.Color(255, 153, 153));
        txtAjuste.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtAjuste.setText("AJUSTE");
        jPanel1.add(txtAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        txtTIPOUNIDAD.setEditable(false);
        txtTIPOUNIDAD.setBackground(new java.awt.Color(255, 255, 102));
        txtTIPOUNIDAD.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTIPOUNIDAD.setText("UNIDAD");
        jPanel1.add(txtTIPOUNIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        txtTIPOLIQUIDOOOOOO.setEditable(false);
        txtTIPOLIQUIDOOOOOO.setBackground(new java.awt.Color(255, 255, 102));
        txtTIPOLIQUIDOOOOOO.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTIPOLIQUIDOOOOOO.setText("LIQUIDO");
        jPanel1.add(txtTIPOLIQUIDOOOOOO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        lblCuentas.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblCuentas.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentas.setText("Cuentas Pasivo :");
        lblCuentas.setToolTipText("");
        jPanel1.add(lblCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, -1));

        jComboBoxCuentas.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(jComboBoxCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 240, -1));

        lblcuentaIngreso.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblcuentaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        lblcuentaIngreso.setText("Cuenta Ingreso :");
        jPanel1.add(lblcuentaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, -1, -1));

        jComboBoxCuentasIngreso.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(jComboBoxCuentasIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 240, -1));

        jComboBoxCuentasInventario.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(jComboBoxCuentasInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 240, -1));

        txtDolarHoy.setEditable(false);
        txtDolarHoy.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtDolarHoy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDolarHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 170, 150, -1));

        lblTasaDelDolar.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTasaDelDolar.setForeground(new java.awt.Color(255, 255, 255));
        lblTasaDelDolar.setText("Tasa del Dolar BCV  :");
        jPanel1.add(lblTasaDelDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, -1, 50));

        lblTotalEnBolivares.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTotalEnBolivares.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalEnBolivares.setText("Total En Bolivares :");
        lblTotalEnBolivares.setToolTipText("");
        jPanel1.add(lblTotalEnBolivares, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, 200, 30));

        txtTotalEnBolivares.setEditable(false);
        txtTotalEnBolivares.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jPanel1.add(txtTotalEnBolivares, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 230, 190, 30));

        lblTotalEnDolares.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTotalEnDolares.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalEnDolares.setText("Total En Dolares :");
        jPanel1.add(lblTotalEnDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, -1, 40));

        txtTotalEnDolares.setEditable(false);
        txtTotalEnDolares.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jPanel1.add(txtTotalEnDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 280, 150, -1));

        lblBuscarAlmacen.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblBuscarAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarAlmacen.setText("Buscar :");
        jPanel1.add(lblBuscarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, -1, 40));

        txtEstanteAlmacen.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtEstanteAlmacen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEstanteAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 150, -1));

        lblCaoacidad.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblCaoacidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCaoacidad.setText("Capacidad :");
        jPanel1.add(lblCaoacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 150, 30));

        txtBuscarAlmacen.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(txtBuscarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 260, 110, -1));

        btbRealizarAjuste.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btbRealizarAjuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/REALIZARSALIDA.png"))); // NOI18N
        btbRealizarAjuste.setText("Realizar Ajuste");
        btbRealizarAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRealizarAjusteActionPerformed(evt);
            }
        });
        jPanel1.add(btbRealizarAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 240, 50));

        txtCapacidadAlmacen.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtCapacidadAlmacen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCapacidadAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 200, 30));

        btbRealizarAjusteUnidad.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btbRealizarAjusteUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/REALIZARSALIDA.png"))); // NOI18N
        btbRealizarAjusteUnidad.setText("Realizar Ajuste");
        btbRealizarAjusteUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRealizarAjusteUnidadActionPerformed(evt);
            }
        });
        jPanel1.add(btbRealizarAjusteUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 240, 50));

        lblEstante.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblEstante.setForeground(new java.awt.Color(255, 255, 255));
        lblEstante.setText("Estante :");
        jPanel1.add(lblEstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 110, -1));

        btbRealizarAjusteLiquido.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btbRealizarAjusteLiquido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/REALIZARSALIDA.png"))); // NOI18N
        btbRealizarAjusteLiquido.setText("Realizar Ajuste");
        btbRealizarAjusteLiquido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRealizarAjusteLiquidoActionPerformed(evt);
            }
        });
        jPanel1.add(btbRealizarAjusteLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 240, 50));

        TablaAlmacen.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneAlmacen.setViewportView(TablaAlmacen);

        jPanel1.add(jScrollPaneAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 1220, 330));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/FondoCompleto.png"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1410, 760));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbRegistrarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRegistrarAlmacenActionPerformed

        try {
            Vali.registrarAlmacenValidado();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbRegistrarAlmacenActionPerformed

    private void btbVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVolverMenuActionPerformed

   


        // TODO add your handling code here:
    }//GEN-LAST:event_btbVolverMenuActionPerformed

    private void btbActualizarALmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbActualizarALmacenActionPerformed

ct.ActualizarAlmacen();

        // TODO add your handling code here:
    }//GEN-LAST:event_btbActualizarALmacenActionPerformed

    private void btbCancelarActualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarActualizacionActionPerformed


ct.CancelarActualizaciondeAlmacen();
        // TODO add your handling code here:
    }//GEN-LAST:event_btbCancelarActualizacionActionPerformed

    private void btbConfirmarActualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConfirmarActualizacionActionPerformed
        try {
            Vali.actualizarAlmacenValidado();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbConfirmarActualizacionActionPerformed

    private void btbEliminarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEliminarAlmacenActionPerformed


almacenDao.EliminarConSeguridad();
        // TODO add your handling code here:
    }//GEN-LAST:event_btbEliminarAlmacenActionPerformed

    private void btbREALIZARSALIDASOLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbREALIZARSALIDASOLIDOActionPerformed
        try {
            SlSolido.ValidarSalidaSolido();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbREALIZARSALIDASOLIDOActionPerformed

    private void btbRealizarAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRealizarAjusteActionPerformed
        try {
            AjsuteSolido.RealizarAjusteSolidoValidado();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbRealizarAjusteActionPerformed

    private void btbRealizarSalidaUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRealizarSalidaUnidadActionPerformed


        try {
            slUnida.ValidarSalidaUNIdad();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbRealizarSalidaUnidadActionPerformed

    private void btbRealizarAjusteUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRealizarAjusteUnidadActionPerformed
        try {
            AjusteUnidad.ValidarAjusteUnidad();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbRealizarAjusteUnidadActionPerformed

    private void btbREALIZARSALIDALIQUIDOooooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbREALIZARSALIDALIQUIDOooooActionPerformed

        try {
            SlVALI.RealizarSalidaLiquidoValidada();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbREALIZARSALIDALIQUIDOooooActionPerformed

    private void btbRealizarAjusteLiquidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRealizarAjusteLiquidoActionPerformed
        try {
            AjusteLiquido.validarAjusteLiquido();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestionar_Almacenn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbRealizarAjusteLiquidoActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    
    Controlador.controladorVisual ct = new Controlador.controladorVisual();
    
    
    Validacion.Validar_Almacen Vali = new Validar_Almacen();
  
    ModeloDAO.InventarioUnidadDAO iv = new  InventarioUnidadDAO();
    ModeloDAO.AlmacenDao almacenDao = new AlmacenDao();
    ModeloDAO.CuentaDao Cu = new  CuentaDao();
    Validacion.Validar_Salida_Liquido SlVALI = new Validar_Salida_Liquido();
ModeloDAO.MovientosDao mv = new MovientosDao();
Validacion.Validar_SALIDA_Unidad slUnida= new Validar_SALIDA_Unidad ();
        Validacion.Validar_Salida_Solido SlSolido = new Validar_Salida_Solido();
        Validacion.ValidaR_Ajuste_Solido AjsuteSolido = new ValidaR_Ajuste_Solido();
        Validacion.Validar_Ajuste_Unidad AjusteUnidad = new Validar_Ajuste_Unidad();
        Validacion.Validar_Ajuste_Liquido AjusteLiquido = new Validar_Ajuste_Liquido();
       ModeloDAO.InventarioLiquidoDao inventarioLiquidoDao = new InventarioLiquidoDao();
       Funciones.BCV bcv = new BCV();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ComboxAla;
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JComboBox<Inventario> JComboxLiquido;
    public static javax.swing.JComboBox<Inventario> JComboxSOLIDO;
    public static javax.swing.JComboBox<Inventario> JComboxSUnidad;
    public static javax.swing.JTable TablaAlmacen;
    public static javax.swing.JButton btbActualizarALmacen;
    public static javax.swing.JButton btbCancelarActualizacion;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbEliminarAlmacen;
    public static javax.swing.JButton btbREALIZARSALIDALIQUIDOoooo;
    public static javax.swing.JButton btbREALIZARSALIDASOLIDO;
    public static javax.swing.JButton btbRealizarAjuste;
    public static javax.swing.JButton btbRealizarAjusteLiquido;
    public static javax.swing.JButton btbRealizarAjusteUnidad;
    public static javax.swing.JButton btbRealizarSalidaUnidad;
    public static javax.swing.JButton btbRegistrarAlmacen;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentas;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentasIngreso;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentasInventario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPaneAlmacen;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblALA;
    public static javax.swing.JLabel lblAccion;
    public static javax.swing.JLabel lblAlaValidacion;
    public static javax.swing.JLabel lblBuscarAlmacen;
    public static javax.swing.JLabel lblCantidad;
    public static javax.swing.JLabel lblCaoacidad;
    public static javax.swing.JLabel lblCapacidadValidacion;
    public static javax.swing.JLabel lblCuentas;
    public static javax.swing.JLabel lblDatelle;
    public static javax.swing.JLabel lblEstante;
    public static javax.swing.JLabel lblEstanteValidacion;
    public static javax.swing.JLabel lblNivel;
    public static javax.swing.JLabel lblNivelValidacion;
    public static javax.swing.JLabel lblPasillo;
    public static javax.swing.JLabel lblPasilloValidacion;
    public static javax.swing.JLabel lblPrecioVenta;
    public static javax.swing.JLabel lblProducto;
    public static javax.swing.JLabel lblTIPOPRODUCTO;
    public static javax.swing.JLabel lblTasaDelDolar;
    public static javax.swing.JLabel lblTotalEnBolivares;
    public static javax.swing.JLabel lblTotalEnDolares;
    public static javax.swing.JLabel lblValidacionPrecioVentaLiquido;
    public static javax.swing.JLabel lblValidacionPrecioVentaSolido;
    public static javax.swing.JLabel lblValidacionPrecioVentaUnidad;
    public static javax.swing.JLabel lblValidadarComboxLIQUIDOAJUSTE1;
    public static javax.swing.JLabel lblValidadarComboxLiquido;
    public static javax.swing.JLabel lblValidadarComboxSolido;
    public static javax.swing.JLabel lblValidadarComboxSolidoAjuste;
    public static javax.swing.JLabel lblValidadarComboxUNIDADAJUSTE;
    public static javax.swing.JLabel lblValidadarComboxUnidad;
    public static javax.swing.JLabel lblValidarCantidadAJUSTELIQUIDO;
    public static javax.swing.JLabel lblValidarCantidadAJUSTEUNIDAD;
    public static javax.swing.JLabel lblValidarCantidadAjusteSolido;
    public static javax.swing.JLabel lblValidarCantidadLiquido;
    public static javax.swing.JLabel lblValidarCantidadSolido;
    public static javax.swing.JLabel lblValidarCantidadSolido1;
    public static javax.swing.JLabel lblValidarDetalleAjusteLIQUIDO;
    public static javax.swing.JLabel lblValidarDetalleAjusteSolido;
    public static javax.swing.JLabel lblValidarDetalleAjusteUNIDAD;
    public static javax.swing.JLabel lblValidarDetalleLiquyido;
    public static javax.swing.JLabel lblValidarDetalleSOLIDO;
    public static javax.swing.JLabel lblValidarDetalleUnidad;
    public static javax.swing.JLabel lblcuentaIngreso;
    public static javax.swing.JTextField txtAjuste;
    public static javax.swing.JTextField txtBuscarAlmacen;
    public static javax.swing.JTextField txtCantidadAjusteLIQUIDO;
    public static javax.swing.JTextField txtCantidadAjusteSolido;
    public static javax.swing.JTextField txtCantidadAjusteUNIDAD;
    public static javax.swing.JTextField txtCantidadLiquido;
    public static javax.swing.JTextField txtCantidadSolido;
    public static javax.swing.JTextField txtCantidadUnidad;
    public static javax.swing.JTextField txtCapacidadAlmacen;
    public static javax.swing.JTextField txtDatelleAjsuteLIQUIDO;
    public static javax.swing.JTextField txtDatelleAjsuteSolido;
    public static javax.swing.JTextField txtDatelleAjsuteUNIDAD;
    public static javax.swing.JTextField txtDatelleLiquido;
    public static javax.swing.JTextField txtDatelleSolido;
    public static javax.swing.JTextField txtDatelleUnidad;
    public static javax.swing.JTextField txtDolarHoy;
    public static javax.swing.JTextField txtEstanteAlmacen;
    public static javax.swing.JTextField txtIDAlmacen;
    public static javax.swing.JTextField txtNivel;
    public static javax.swing.JTextField txtPasillolmacen;
    public static javax.swing.JTextField txtPrecioVentaLiquido;
    public static javax.swing.JTextField txtPrecioVentaSOLIDONuevo;
    public static javax.swing.JTextField txtPrecioVentaUnidad;
    public static javax.swing.JTextField txtSALIDA;
    public static javax.swing.JTextField txtTIPOLIQUIDO;
    public static javax.swing.JTextField txtTIPOLIQUIDOOOOOO;
    public static javax.swing.JTextField txtTIPOUNIDAD;
    public static javax.swing.JTextField txtTotalEnBolivares;
    public static javax.swing.JTextField txtTotalEnDolares;
    // End of variables declaration//GEN-END:variables
}
