
package Vista_Almacen;

/**
 *
 * @author avila
 */
public class Vista_Registrar_Almacen extends javax.swing.JFrame {
    
   

    /**
     * Creates new form Vista_Almacen
     */
    public Vista_Registrar_Almacen() {
        initComponents();
        setTitle("Almacen");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPasillo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxAla = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEstante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAlmacen = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarProductoEnTabla = new javax.swing.JTextField();
        btbVolverMenu = new javax.swing.JButton();
        btbEliminar = new javax.swing.JButton();
        btbActualizar = new javax.swing.JButton();
        btbRegistrar = new javax.swing.JButton();
        btbConfirmarActualizacion = new javax.swing.JButton();
        btbCancelarActualizacion = new javax.swing.JButton();
        lblValidarPasillo = new javax.swing.JLabel();
        LblValidarnivel = new javax.swing.JLabel();
        LblValidarcapacidad = new javax.swing.JLabel();
        LblValidarestante = new javax.swing.JLabel();
        LblValidarAla = new javax.swing.JLabel();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Almacén");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 110, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pasillo :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        txtPasillo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtPasillo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPasillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 190, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ala :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jComboBoxAla.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jComboBoxAla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IZQUIERDA", "DERECHA" }));
        jPanel1.add(jComboBoxAla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nivel :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        txtNivel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtNivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 160, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Capacidad :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        txtCapacidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCapacidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 160, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estante :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, -1, -1));

        txtEstante.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtEstante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstante.setToolTipText("");
        jPanel1.add(txtEstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, 120, -1));

        TablaAlmacen.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        TablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaAlmacen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 1220, 230));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 320, -1, -1));

        txtBuscarProductoEnTabla.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoEnTabla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProductoEnTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 320, 90, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, -1, 40));

        btbEliminar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btbEliminar.setText("Eliminar");
        jPanel1.add(btbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, 140, 40));

        btbActualizar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btbActualizar.setText("Actualizar");
        btbActualizar.addActionListener(this::btbActualizarActionPerformed);
        jPanel1.add(btbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, -1, 40));

        btbRegistrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbRegistrar.setText("Registrar");
        jPanel1.add(btbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 660, -1, 40));

        btbConfirmarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbConfirmarActualizacion.setText("Confirmar Actualización");
        jPanel1.add(btbConfirmarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, 280, 40));

        btbCancelarActualizacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbCancelarActualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-x.png"))); // NOI18N
        btbCancelarActualizacion.setText("Cancelar ");
        jPanel1.add(btbCancelarActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 660, 150, 40));

        lblValidarPasillo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarPasillo.setForeground(new java.awt.Color(255, 0, 0));
        lblValidarPasillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblValidarPasillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, 20));

        LblValidarnivel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LblValidarnivel.setForeground(new java.awt.Color(255, 0, 0));
        LblValidarnivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LblValidarnivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 290, 20));

        LblValidarcapacidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LblValidarcapacidad.setForeground(new java.awt.Color(255, 0, 0));
        LblValidarcapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LblValidarcapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 310, 20));

        LblValidarestante.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LblValidarestante.setForeground(new java.awt.Color(255, 0, 0));
        LblValidarestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LblValidarestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 250, 20));

        LblValidarAla.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        LblValidarAla.setForeground(new java.awt.Color(255, 0, 0));
        LblValidarAla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LblValidarAla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 190, 20));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        FondoPantalla.setText("jLabel1");
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1430, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1427, 743));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JLabel LblValidarAla;
    public static javax.swing.JLabel LblValidarcapacidad;
    public static javax.swing.JLabel LblValidarestante;
    public static javax.swing.JLabel LblValidarnivel;
    public static javax.swing.JTable TablaAlmacen;
    public static javax.swing.JButton btbActualizar;
    public static javax.swing.JButton btbCancelarActualizacion;
    public static javax.swing.JButton btbConfirmarActualizacion;
    public static javax.swing.JButton btbEliminar;
    public static javax.swing.JButton btbRegistrar;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<String> jComboBoxAla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblValidarPasillo;
    public static javax.swing.JTextField txtBuscarProductoEnTabla;
    public static javax.swing.JTextField txtCapacidad;
    public static javax.swing.JTextField txtEstante;
    public static javax.swing.JTextField txtNivel;
    public static javax.swing.JTextField txtPasillo;
    // End of variables declaration//GEN-END:variables
}
