/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Almacen;

import Modelo.Inventario;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class Vista_Salida_Liquido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_Salida_Liquido.class.getName());

    /**
     * Creates new form Vista_Salida_Liquido
     */
    public Vista_Salida_Liquido() {
        initComponents();
        setTitle("Salida Liquido");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AccionSalidaLiquido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Txttiposalidaliquido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipoProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxProductoLiquido = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaInformacionProducto = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtCantidadSalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalEnBolivares = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalEnDolares = new javax.swing.JTextField();
        txtTasaDelDolar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCuentaPasivo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxCuentaIngreso = new javax.swing.JComboBox<>();
        btbVolverAlMenu = new javax.swing.JButton();
        btbRealizarMovimiento = new javax.swing.JButton();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccionSalidaLiquido.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        AccionSalidaLiquido.setForeground(new java.awt.Color(255, 255, 255));
        AccionSalidaLiquido.setText("Acción:");
        jPanel1.add(AccionSalidaLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salida Liquido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        Txttiposalidaliquido.setEditable(false);
        Txttiposalidaliquido.setBackground(new java.awt.Color(102, 255, 102));
        Txttiposalidaliquido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Txttiposalidaliquido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txttiposalidaliquido.setText("SALIDA");
        jPanel1.add(Txttiposalidaliquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 100, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ssitema de inventario");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtTipoProducto.setEditable(false);
        txtTipoProducto.setBackground(new java.awt.Color(255, 255, 0));
        txtTipoProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTipoProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProducto.setText("LIQUIDO");
        jPanel1.add(txtTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 100, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jComboBoxProductoLiquido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel1.add(jComboBoxProductoLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 580, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        txtBuscarProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 80, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Información Completa del Producto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        TextAreaInformacionProducto.setEditable(false);
        TextAreaInformacionProducto.setBackground(new java.awt.Color(255, 255, 255));
        TextAreaInformacionProducto.setColumns(20);
        TextAreaInformacionProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        TextAreaInformacionProducto.setRows(5);
        jScrollPane1.setViewportView(TextAreaInformacionProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 400, 280));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        txtCantidadSalida.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidadSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 110, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Precio de Venta Unitario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBackground(new java.awt.Color(0, 255, 0));
        txtPrecioVenta.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 130, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tasa del Dolar BCV:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total En Bolivares:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        txtTotalEnBolivares.setEditable(false);
        txtTotalEnBolivares.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTotalEnBolivares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotalEnBolivares, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 150, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total En Dolares:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        txtTotalEnDolares.setEditable(false);
        txtTotalEnDolares.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTotalEnDolares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotalEnDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 150, -1));

        txtTasaDelDolar.setEditable(false);
        txtTasaDelDolar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTasaDelDolar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTasaDelDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 110, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Detalle:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        txtDetalle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtDetalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 400, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cuenta Pasivo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, -1, -1));

        jComboBoxCuentaPasivo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(jComboBoxCuentaPasivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, 300, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cuenta Ingreso:");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, -1, -1));

        jComboBoxCuentaIngreso.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(jComboBoxCuentaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 530, 290, -1));

        btbVolverAlMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverAlMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverAlMenu.setText("Volver");
        jPanel1.add(btbVolverAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 140, 40));

        btbRealizarMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRealizarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbRealizarMovimiento.setText("Realizar Movimiento");
        jPanel1.add(btbRealizarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 652, -1, 40));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1390, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1385, 741));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AccionSalidaLiquido;
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JTextArea TextAreaInformacionProducto;
    public static javax.swing.JTextField Txttiposalidaliquido;
    public static javax.swing.JButton btbRealizarMovimiento;
    public static javax.swing.JButton btbVolverAlMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaIngreso;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaPasivo;
    public static javax.swing.JComboBox<Inventario> jComboBoxProductoLiquido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtBuscarProducto;
    public static javax.swing.JTextField txtCantidadSalida;
    public static javax.swing.JTextField txtDetalle;
    public static javax.swing.JTextField txtPrecioVenta;
    public static javax.swing.JTextField txtTasaDelDolar;
    public static javax.swing.JTextField txtTipoProducto;
    public static javax.swing.JTextField txtTotalEnBolivares;
    public static javax.swing.JTextField txtTotalEnDolares;
    // End of variables declaration//GEN-END:variables
}
