/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Almacen;

import Modelo.Inventario;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class Vista_Salida_Unidad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_Salida_Unidad.class.getName());

    /**
     * Creates new form Vista_Salida_Unidad
     */
    public Vista_Salida_Unidad() {
        initComponents();
        setTitle("Salida de Unidad");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLajs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAccionSalida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipoProductoUnidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxProductoUnida = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtBuscaProductoCombox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadUnida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioVentaUnitario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalEnBolivares = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotalEnDolares = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        btbVolverMenu = new javax.swing.JButton();
        btbRealizarMovimiento = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtInformacionProducto = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtTasaDolar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCuenta = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxIngreson = new javax.swing.JComboBox<>();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLajs.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblLajs.setForeground(new java.awt.Color(255, 255, 255));
        lblLajs.setText("Salida Unidad");
        jPanel1.add(lblLajs, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acción :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        txtAccionSalida.setEditable(false);
        txtAccionSalida.setBackground(new java.awt.Color(153, 255, 153));
        txtAccionSalida.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtAccionSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccionSalida.setText("SALIDA");
        jPanel1.add(txtAccionSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 100, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo Producto :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtTipoProductoUnidad.setEditable(false);
        txtTipoProductoUnidad.setBackground(new java.awt.Color(255, 204, 51));
        txtTipoProductoUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTipoProductoUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoProductoUnidad.setText("UNIDAD");
        jPanel1.add(txtTipoProductoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jComboBoxProductoUnida.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jPanel1.add(jComboBoxProductoUnida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 540, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        txtBuscaProductoCombox.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscaProductoCombox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBuscaProductoCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        txtCantidadUnida.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidadUnida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidadUnida, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 240, 110, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Precio de Venta Unitario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 20));

        txtPrecioVentaUnitario.setEditable(false);
        txtPrecioVentaUnitario.setBackground(new java.awt.Color(102, 255, 102));
        txtPrecioVentaUnitario.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPrecioVentaUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVentaUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 120, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total En Bolivares:");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txtTotalEnBolivares.setEditable(false);
        txtTotalEnBolivares.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTotalEnBolivares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotalEnBolivares, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 170, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total En Dolares:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, 20));

        txtTotalEnDolares.setEditable(false);
        txtTotalEnDolares.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTotalEnDolares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotalEnDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 120, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Detalle:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        txtDetalle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtDetalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 440, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, -1, 40));

        btbRealizarMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRealizarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbRealizarMovimiento.setText("Realizar Movimiento");
        jPanel1.add(btbRealizarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, -1, 40));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Información Completa del Producto");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, -1, 30));

        TxtInformacionProducto.setEditable(false);
        TxtInformacionProducto.setColumns(20);
        TxtInformacionProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        TxtInformacionProducto.setRows(5);
        jScrollPane1.setViewportView(TxtInformacionProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 440, 330));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tasa del Dolar BCV:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, -1));

        txtTasaDolar.setEditable(false);
        txtTasaDolar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTasaDolar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTasaDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, 100, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cuenta Pasivo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 531, -1, 20));

        jComboBoxCuenta.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(jComboBoxCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, 320, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cuenta Ingreso:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, -1, -1));

        jComboBoxIngreson.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(jComboBoxIngreson, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, 320, -1));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1460, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JTextArea TxtInformacionProducto;
    public static javax.swing.JButton btbRealizarMovimiento;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuenta;
    public static javax.swing.JComboBox<cuenta> jComboBoxIngreson;
    public static javax.swing.JComboBox<Inventario> jComboBoxProductoUnida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLajs;
    public static javax.swing.JTextField txtAccionSalida;
    public static javax.swing.JTextField txtBuscaProductoCombox;
    public static javax.swing.JTextField txtCantidadUnida;
    public static javax.swing.JTextField txtDetalle;
    public static javax.swing.JTextField txtPrecioVentaUnitario;
    public static javax.swing.JTextField txtTasaDolar;
    public static javax.swing.JTextField txtTipoProductoUnidad;
    public static javax.swing.JTextField txtTotalEnBolivares;
    public static javax.swing.JTextField txtTotalEnDolares;
    // End of variables declaration//GEN-END:variables
}
