/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Almacen;

import Modelo.Inventario;
import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class Vista_Salida_Solido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_Salida_Solido.class.getName());

    /**
     * Creates new form Vista_Salida_Solido
     */
    public Vista_Salida_Solido() {
        initComponents();
        setTitle("Salida Solido");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSalidaSolido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProductoSolido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxProductoSolido = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarProductoSolido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioVentaUnitario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotalEnBolivares = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalEnDolares = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        btbVolver = new javax.swing.JButton();
        btbRealizarMovimiento = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTasaBCV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacionProducto = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxCuantaPasivo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxIngreso = new javax.swing.JComboBox<>();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salida Sólido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        txtSalidaSolido.setEditable(false);
        txtSalidaSolido.setBackground(new java.awt.Color(153, 255, 153));
        txtSalidaSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtSalidaSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalidaSolido.setText("SALIDA");
        txtSalidaSolido.addActionListener(this::txtSalidaSolidoActionPerformed);
        jPanel1.add(txtSalidaSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo Producto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtProductoSolido.setEditable(false);
        txtProductoSolido.setBackground(new java.awt.Color(255, 102, 102));
        txtProductoSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtProductoSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProductoSolido.setText("Solido");
        jPanel1.add(txtProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 120, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jComboBoxProductoSolido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jPanel1.add(jComboBoxProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 560, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        txtBuscarProductoSolido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtBuscarProductoSolido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarProductoSolido.setToolTipText("");
        jPanel1.add(txtBuscarProductoSolido, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 90, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 110, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio de Venta Unitario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        txtPrecioVentaUnitario.setEditable(false);
        txtPrecioVentaUnitario.setBackground(new java.awt.Color(102, 255, 102));
        txtPrecioVentaUnitario.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtPrecioVentaUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrecioVentaUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 130, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total En Bolivares:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        txtTotalEnBolivares.setEditable(false);
        txtTotalEnBolivares.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTotalEnBolivares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotalEnBolivares, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 150, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Total En Dolares:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        txtTotalEnDolares.setEditable(false);
        txtTotalEnDolares.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTotalEnDolares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotalEnDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 150, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Detalle:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        txtDetalle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtDetalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDetalle.setToolTipText("");
        jPanel1.add(txtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 420, -1));

        btbVolver.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolver.setText("Volver");
        jPanel1.add(btbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 642, 130, 40));

        btbRealizarMovimiento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbRealizarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Historial De Movimiento.png"))); // NOI18N
        btbRealizarMovimiento.setText("Realizar Movimiento");
        jPanel1.add(btbRealizarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, 40));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tasa del Dolar BCV:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        txtTasaBCV.setEditable(false);
        txtTasaBCV.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtTasaBCV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTasaBCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 120, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Información Completa del Producto");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, -1, -1));

        txtInformacionProducto.setEditable(false);
        txtInformacionProducto.setColumns(20);
        txtInformacionProducto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtInformacionProducto.setRows(5);
        jScrollPane1.setViewportView(txtInformacionProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 400, 300));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cuenta Pasivo:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 510, -1, -1));

        jComboBoxCuantaPasivo.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboBoxCuantaPasivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, 300, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cuenta Ingreso:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, -1, -1));

        jComboBoxIngreso.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel1.add(jComboBoxIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 290, -1));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 743));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalidaSolidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaSolidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaSolidoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JButton btbRealizarMovimiento;
    public static javax.swing.JButton btbVolver;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuantaPasivo;
    public static javax.swing.JComboBox<cuenta> jComboBoxIngreso;
    public static javax.swing.JComboBox<Inventario> jComboBoxProductoSolido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtBuscarProductoSolido;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtDetalle;
    public static javax.swing.JTextArea txtInformacionProducto;
    public static javax.swing.JTextField txtPrecioVentaUnitario;
    public static javax.swing.JTextField txtProductoSolido;
    public static javax.swing.JTextField txtSalidaSolido;
    public static javax.swing.JTextField txtTasaBCV;
    public static javax.swing.JTextField txtTotalEnBolivares;
    public static javax.swing.JTextField txtTotalEnDolares;
    // End of variables declaration//GEN-END:variables
}
