
package Vista_Usuari_Empleado;

import Modelo.ConexiónBD;
import ModeloDAO.UsurioDAO;
import controladorLogin.ControladorLogin;
import dictionary.AutoCorrectorGlobal;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import javax.swing.ImageIcon.*;
public class Login_Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Principal
     */
    public Login_Ingreso() {
        initComponents(); 
         setTitle("Login");
          setExtendedState(MAXIMIZED_BOTH);
          Ct.IniciarHoraLogin();
        setLocationRelativeTo(null);
    u.eventoLblRecuperar(lblRecuparerContrase, this);
    AutoCorrectorGlobal.aplicar(this);
    txtUsuario.setText("airan");
    txtPasContraseña.setText("Fenix.20*");
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtbIniciar = new javax.swing.JButton();
        txtPasContraseña = new javax.swing.JPasswordField();
        lblHora = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblRecuparerContrase = new javax.swing.JLabel();
        MostrarContraseña = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE GESTIÓN INVENTARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 470, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 130, -1));

        txtUsuario.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 310, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 170, -1));

        BtbIniciar.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        BtbIniciar.setForeground(new java.awt.Color(51, 51, 51));
        BtbIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iniciar seccion 2.png"))); // NOI18N
        BtbIniciar.setText("INICIAR SESIÓN");
        BtbIniciar.setBorder(null);
        BtbIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtbIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(BtbIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 220, 40));

        txtPasContraseña.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtPasContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPasContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 300, 30));

        lblHora.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 20));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 130, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 590, 20));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REPUESTOS Y ACCESORIOS RAC 2012 C.A");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 420, 20));

        lblRecuparerContrase.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblRecuparerContrase.setForeground(new java.awt.Color(51, 255, 51));
        lblRecuparerContrase.setText("¿Olvidaste tu contraseña?");
        lblRecuparerContrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRecuparerContraseMousePressed(evt);
            }
        });
        jPanel1.add(lblRecuparerContrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, -1, -1));

        MostrarContraseña.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        MostrarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        MostrarContraseña.setText("Haz clic para ver su clave");
        MostrarContraseña.setToolTipText("");
        MostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 280, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cabra.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 290, 190));

        jLabel5.setFont(new java.awt.Font("Harlow Solid Italic", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(1606, 450));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void BtbIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtbIniciarActionPerformed
          
    }//GEN-LAST:event_BtbIniciarActionPerformed

    private void lblRecuparerContraseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuparerContraseMousePressed
    // TODO add your handling code here:
    }//GEN-LAST:event_lblRecuparerContraseMousePressed

    private void MostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarContraseñaActionPerformed

   
    
    ModeloDAO.UsurioDAO u = new UsurioDAO();
  Controlador.controladorVisual Ct = new  Controlador.controladorVisual();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtbIniciar;
    public static javax.swing.JCheckBox MostrarContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblRecuparerContrase;
    public static javax.swing.JPasswordField txtPasContraseña;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
