/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Usuari_Empleado;

import Controlador.controladorVisual;
import Modelo.Usuario;
import ModeloDAO.MovientosDao;
import Reportes.Reporte_Ajuste_inventario;
import Reportes.Reporte_De_Ganancia_por_producto;
import Reportes.Reporte_entrada_Inventario;
import Reportes.Reporte_mas_vendidos;
import Reportes.Reporte_producto_baja_rotacion;
import Reportes.Reporte_salida_inventario;
import Reportes.Reportes_Stock_Bajo;
import Reportes.Reportes_de_proveedores;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.WindowConstants;
/**
 *
 * @author Adrian
 */
public class Menu_Sistema extends javax.swing.JFrame {

 private static Menu_Sistema instancia;
    

    public static Menu_Sistema getInstancia() {
        if (instancia == null) {
            instancia = new Menu_Sistema();
        }
        return instancia;
    }

    public Menu_Sistema() {
        initComponents();
        setTitle("Inicio");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ct.IniciarHora();
        this.setExtendedState(Menu_Sistema.MAXIMIZED_BOTH);
        btbGestionarAlmacen.setVisible(false);
      
        btbGestionarLibroContable.setVisible(false);
        btbGestionarReporte.setVisible(false);
    }


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btbGestionarAlmacen = new javax.swing.JButton();
        btbGestionarReporte = new javax.swing.JButton();
        BotonCerraSeccion = new javax.swing.JButton();
        btbGestionarLibroContable = new javax.swing.JButton();
        lblUsuarioENLinea = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JMenu = new javax.swing.JMenuBar();
        Menu_Inicial_Producto = new javax.swing.JMenu();
        MenuCategoria = new javax.swing.JMenuItem();
        MenuMarca = new javax.swing.JMenuItem();
        jMenuProductoLiquido = new javax.swing.JMenuItem();
        jMenuProductoSolido = new javax.swing.JMenuItem();
        jMenuRegistrarUnidad = new javax.swing.JMenuItem();
        Menu_Inicial_Empleado = new javax.swing.JMenu();
        Jmenu_Abri_Empleado = new javax.swing.JMenuItem();
        jMenuIuSUARIOS = new javax.swing.JMenuItem();
        Menu_inicial_proveedor = new javax.swing.JMenu();
        Menu_cotizacion = new javax.swing.JMenuItem();
        Jmenu_abrir_Proveedor = new javax.swing.JMenuItem();
        JMenu_Iniciar_Almacen = new javax.swing.JMenu();
        jMenuAbrirAlmacen = new javax.swing.JMenuItem();
        jMenuItemLiquidoSalida = new javax.swing.JMenuItem();
        jMenuISALIDA_SOLIDO = new javax.swing.JMenuItem();
        jMenuItemUnidaSalida = new javax.swing.JMenuItem();
        jMenuItemAjusteLiquiod = new javax.swing.JMenuItem();
        jMenuItemAjusteSolido = new javax.swing.JMenuItem();
        jMenuItemAjusteUnidad = new javax.swing.JMenuItem();
        jMenu_Inventario = new javax.swing.JMenu();
        jMenuInventarioLiquido = new javax.swing.JMenuItem();
        jMenuItemInventarioSolido = new javax.swing.JMenuItem();
        jMenuIInventarioUnidad = new javax.swing.JMenuItem();
        jMenuLibroContable = new javax.swing.JMenu();
        JmenuLibroMayor = new javax.swing.JMenuItem();
        jMenuLibroDIARIO = new javax.swing.JMenuItem();
        jMenuItemCuentasContables = new javax.swing.JMenuItem();
        Menu_Reportes_Sistema = new javax.swing.JMenu();
        Menu_Salidas_Inventario_Reporte = new javax.swing.JMenuItem();
        Menu_Reporte_Proveedores = new javax.swing.JMenuItem();
        Menu_Reporte_Margen_Ganancias = new javax.swing.JMenuItem();
        Menu_Reporte_Ganancias = new javax.swing.JMenuItem();
        Menu_Reportes_Productos_Vendidos = new javax.swing.JMenuItem();
        Menu_Ajustes_Inventario = new javax.swing.JMenuItem();
        Menu_Inventario_Bajo_Reporte = new javax.swing.JMenuItem();
        Menu_Productos_bajarotacion = new javax.swing.JMenuItem();
        Menu_Reportes_Entradas_Inventario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHora.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 420, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 290, 20));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPUESTOS Y ACCESORIOS RAC 2012 C.A");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 410, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, 20));

        btbGestionarAlmacen.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbGestionarAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Almacen.png"))); // NOI18N
        btbGestionarAlmacen.setText("GESTIONAR ALMACÉN");
        btbGestionarAlmacen.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(51, 51, 0)));
        btbGestionarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGestionarAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btbGestionarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 290, 120));

        btbGestionarReporte.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbGestionarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Reportes.png"))); // NOI18N
        btbGestionarReporte.setText(" INFORMER Y REPORTES");
        btbGestionarReporte.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 0)));
        btbGestionarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGestionarReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btbGestionarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, 300, 120));

        BotonCerraSeccion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        BotonCerraSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar-sesion.png"))); // NOI18N
        BotonCerraSeccion.setText("Cerrar Sesión");
        BotonCerraSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerraSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(BotonCerraSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        btbGestionarLibroContable.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbGestionarLibroContable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/libro-de-registro.png"))); // NOI18N
        btbGestionarLibroContable.setText(" LIBRO CONTABLE");
        btbGestionarLibroContable.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 208, 20)));
        btbGestionarLibroContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGestionarLibroContableActionPerformed(evt);
            }
        });
        jPanel1.add(btbGestionarLibroContable, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 320, 120));

        lblUsuarioENLinea.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblUsuarioENLinea.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUsuarioENLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 160, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("Usuario en linea: ");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 740));

        Menu_Inicial_Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Producto Pequeno.png"))); // NOI18N
        Menu_Inicial_Producto.setText("Productos");

        MenuCategoria.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        MenuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/categoria 32.png"))); // NOI18N
        MenuCategoria.setText("Categoria");
        Menu_Inicial_Producto.add(MenuCategoria);

        MenuMarca.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        MenuMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/marca 32.png"))); // NOI18N
        MenuMarca.setText("Marca");
        Menu_Inicial_Producto.add(MenuMarca);

        jMenuProductoLiquido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuProductoLiquido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceite-de-motor 32.png"))); // NOI18N
        jMenuProductoLiquido.setText("Registrar Liquido");
        Menu_Inicial_Producto.add(jMenuProductoLiquido);

        jMenuProductoSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jMenuProductoSolido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/piezas-de-repuesto 32.png"))); // NOI18N
        jMenuProductoSolido.setText("Registrar Sólido");
        Menu_Inicial_Producto.add(jMenuProductoSolido);

        jMenuRegistrarUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jMenuRegistrarUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Unidad 32.png"))); // NOI18N
        jMenuRegistrarUnidad.setText("Registrar Unidad");
        Menu_Inicial_Producto.add(jMenuRegistrarUnidad);

        JMenu.add(Menu_Inicial_Producto);

        Menu_Inicial_Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Empleado 32.png"))); // NOI18N
        Menu_Inicial_Empleado.setText("Empleados");

        Jmenu_Abri_Empleado.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Jmenu_Abri_Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entrar 32.png"))); // NOI18N
        Jmenu_Abri_Empleado.setText("Abrir");
        Menu_Inicial_Empleado.add(Jmenu_Abri_Empleado);

        jMenuIuSUARIOS.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuIuSUARIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuarios 32.png"))); // NOI18N
        jMenuIuSUARIOS.setText("Usuarios");
        Menu_Inicial_Empleado.add(jMenuIuSUARIOS);

        JMenu.add(Menu_Inicial_Empleado);

        Menu_inicial_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Proveedor.png"))); // NOI18N
        Menu_inicial_proveedor.setText("Proveedor");

        Menu_cotizacion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Menu_cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cotizacion 32.png"))); // NOI18N
        Menu_cotizacion.setText("Cotización");
        Menu_inicial_proveedor.add(Menu_cotizacion);

        Jmenu_abrir_Proveedor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Jmenu_abrir_Proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entrar 32.png"))); // NOI18N
        Jmenu_abrir_Proveedor.setText("Abrir");
        Menu_inicial_proveedor.add(Jmenu_abrir_Proveedor);

        JMenu.add(Menu_inicial_proveedor);

        JMenu_Iniciar_Almacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Almacen 32.png"))); // NOI18N
        JMenu_Iniciar_Almacen.setText("Almacén");

        jMenuAbrirAlmacen.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuAbrirAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Entrar 32.png"))); // NOI18N
        jMenuAbrirAlmacen.setText("Abrir Almacén");
        jMenuAbrirAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirAlmacenActionPerformed(evt);
            }
        });
        JMenu_Iniciar_Almacen.add(jMenuAbrirAlmacen);

        jMenuItemLiquidoSalida.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuItemLiquidoSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceite-de-motor 32.png"))); // NOI18N
        jMenuItemLiquidoSalida.setText("Salida Liquido");
        JMenu_Iniciar_Almacen.add(jMenuItemLiquidoSalida);

        jMenuISALIDA_SOLIDO.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jMenuISALIDA_SOLIDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/SalidaSolido 32.png"))); // NOI18N
        jMenuISALIDA_SOLIDO.setText("Salida Solido");
        JMenu_Iniciar_Almacen.add(jMenuISALIDA_SOLIDO);

        jMenuItemUnidaSalida.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuItemUnidaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/InventarioUnidad 32.png"))); // NOI18N
        jMenuItemUnidaSalida.setText("Salida Unida");
        JMenu_Iniciar_Almacen.add(jMenuItemUnidaSalida);

        jMenuItemAjusteLiquiod.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jMenuItemAjusteLiquiod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AjusteLiquido 32.png"))); // NOI18N
        jMenuItemAjusteLiquiod.setText("Ajuste Liquido");
        JMenu_Iniciar_Almacen.add(jMenuItemAjusteLiquiod);

        jMenuItemAjusteSolido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jMenuItemAjusteSolido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AjusteSolido 32.png"))); // NOI18N
        jMenuItemAjusteSolido.setText("Ajuste Solido");
        jMenuItemAjusteSolido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjusteSolidoActionPerformed(evt);
            }
        });
        JMenu_Iniciar_Almacen.add(jMenuItemAjusteSolido);

        jMenuItemAjusteUnidad.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jMenuItemAjusteUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AjusteUnidad 32.png"))); // NOI18N
        jMenuItemAjusteUnidad.setText("Ajuste Unidad");
        JMenu_Iniciar_Almacen.add(jMenuItemAjusteUnidad);

        JMenu.add(JMenu_Iniciar_Almacen);

        jMenu_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inventario  32.png"))); // NOI18N
        jMenu_Inventario.setText("Inventario");

        jMenuInventarioLiquido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuInventarioLiquido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/InventarioLiquido 32 Nuevo.png"))); // NOI18N
        jMenuInventarioLiquido.setText("Liquido");
        jMenu_Inventario.add(jMenuInventarioLiquido);

        jMenuItemInventarioSolido.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuItemInventarioSolido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/InventarioSolido 32.png"))); // NOI18N
        jMenuItemInventarioSolido.setText(" Sólido");
        jMenu_Inventario.add(jMenuItemInventarioSolido);

        jMenuIInventarioUnidad.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuIInventarioUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/InventarioUnidad 32.png"))); // NOI18N
        jMenuIInventarioUnidad.setText("Unidad");
        jMenu_Inventario.add(jMenuIInventarioUnidad);

        JMenu.add(jMenu_Inventario);

        jMenuLibroContable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/libro-de-registro 32.png"))); // NOI18N
        jMenuLibroContable.setText("Libro Contable");
        jMenuLibroContable.setToolTipText("");

        JmenuLibroMayor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        JmenuLibroMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Amarrilo.png"))); // NOI18N
        JmenuLibroMayor.setText("Libro Mayor");
        jMenuLibroContable.add(JmenuLibroMayor);

        jMenuLibroDIARIO.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuLibroDIARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Amarrilo.png"))); // NOI18N
        jMenuLibroDIARIO.setText("Libro Diario");
        jMenuLibroContable.add(jMenuLibroDIARIO);

        jMenuItemCuentasContables.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jMenuItemCuentasContables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-Amarrilo.png"))); // NOI18N
        jMenuItemCuentasContables.setText("Cuentas Contables");
        jMenuLibroContable.add(jMenuItemCuentasContables);

        JMenu.add(jMenuLibroContable);

        Menu_Reportes_Sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Reportes 32.png"))); // NOI18N
        Menu_Reportes_Sistema.setText("Reportes");

        Menu_Salidas_Inventario_Reporte.setText("Reporte Salidas de Inventario");
        Menu_Salidas_Inventario_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Salidas_Inventario_ReporteActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Salidas_Inventario_Reporte);

        Menu_Reporte_Proveedores.setText("Reporte Proveedores");
        Menu_Reporte_Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Reporte_ProveedoresActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Reporte_Proveedores);

        Menu_Reporte_Margen_Ganancias.setText("Margen de Ganancia");
        Menu_Reporte_Margen_Ganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Reporte_Margen_GananciasActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Reporte_Margen_Ganancias);

        Menu_Reporte_Ganancias.setText("Reporte de Ganancias por Producto");
        Menu_Reporte_Ganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Reporte_GananciasActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Reporte_Ganancias);

        Menu_Reportes_Productos_Vendidos.setText("Reporte Productos mas Vendidos");
        Menu_Reportes_Productos_Vendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Reportes_Productos_VendidosActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Reportes_Productos_Vendidos);

        Menu_Ajustes_Inventario.setText("Reportes Ajustes de Inventario");
        Menu_Ajustes_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Ajustes_InventarioActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Ajustes_Inventario);

        Menu_Inventario_Bajo_Reporte.setText("Reporte de Inventario Bajo");
        Menu_Inventario_Bajo_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Inventario_Bajo_ReporteActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Inventario_Bajo_Reporte);

        Menu_Productos_bajarotacion.setText("Reporte Productos de Baja Rotacion");
        Menu_Productos_bajarotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Productos_bajarotacionActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Productos_bajarotacion);

        Menu_Reportes_Entradas_Inventario.setText("Reportes de Entradas de Inventario");
        Menu_Reportes_Entradas_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Reportes_Entradas_InventarioActionPerformed(evt);
            }
        });
        Menu_Reportes_Sistema.add(Menu_Reportes_Entradas_Inventario);

        JMenu.add(Menu_Reportes_Sistema);

        setJMenuBar(JMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbGestionarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGestionarAlmacenActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_btbGestionarAlmacenActionPerformed

    private void btbGestionarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGestionarReporteActionPerformed

  new Vista_Reporte_Informes.frm_Reportes_Informes().setVisible(true);
  this.dispose();
    }//GEN-LAST:event_btbGestionarReporteActionPerformed

    private void BotonCerraSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerraSeccionActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCerraSeccionActionPerformed

    private void btbGestionarLibroContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGestionarLibroContableActionPerformed

             // TODO add your handling code here:
    }//GEN-LAST:event_btbGestionarLibroContableActionPerformed

    private void Menu_Reporte_GananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Reporte_GananciasActionPerformed
       ganancia_por_producto.mostrar(); 
    }//GEN-LAST:event_Menu_Reporte_GananciasActionPerformed

    private void Menu_Salidas_Inventario_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Salidas_Inventario_ReporteActionPerformed
     reporte_salida_inventario.mostrar();
    }//GEN-LAST:event_Menu_Salidas_Inventario_ReporteActionPerformed

    private void Menu_Reporte_ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Reporte_ProveedoresActionPerformed
       
        reportes_de_proveedores.mostrar();
    }//GEN-LAST:event_Menu_Reporte_ProveedoresActionPerformed

    private void Menu_Reporte_Margen_GananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Reporte_Margen_GananciasActionPerformed
     
Funciones.ReporteMargenGanancia.mostrar();
    }//GEN-LAST:event_Menu_Reporte_Margen_GananciasActionPerformed

    private void Menu_Ajustes_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Ajustes_InventarioActionPerformed
      ajuste_inventario.mostrar(); 
    }//GEN-LAST:event_Menu_Ajustes_InventarioActionPerformed

    private void Menu_Inventario_Bajo_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Inventario_Bajo_ReporteActionPerformed
        stock_Bajo.mostrar(); 
    }//GEN-LAST:event_Menu_Inventario_Bajo_ReporteActionPerformed

    private void Menu_Reportes_Productos_VendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Reportes_Productos_VendidosActionPerformed
        reporte_mas_vendidos.mostrar();   
    }//GEN-LAST:event_Menu_Reportes_Productos_VendidosActionPerformed

    private void Menu_Productos_bajarotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Productos_bajarotacionActionPerformed
      reporte_producto_baja_rotacion.mostrar(); 
    }//GEN-LAST:event_Menu_Productos_bajarotacionActionPerformed

    private void Menu_Reportes_Entradas_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Reportes_Entradas_InventarioActionPerformed
        reporte_entrada_Inventario.mostrar(); 
    }//GEN-LAST:event_Menu_Reportes_Entradas_InventarioActionPerformed

    private void jMenuItemAjusteSolidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjusteSolidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAjusteSolidoActionPerformed

    private void jMenuAbrirAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAbrirAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
  Controlador.controladorVisual ct = new controladorVisual();
   Reportes.Reporte_salida_inventario reporte_salida_inventario = new Reporte_salida_inventario();
   Reportes.Reportes_de_proveedores reportes_de_proveedores = new Reportes_de_proveedores();
   Reportes.Reporte_Ajuste_inventario ajuste_inventario = new Reporte_Ajuste_inventario();
   Reportes.Reporte_De_Ganancia_por_producto ganancia_por_producto = new Reporte_De_Ganancia_por_producto();
   Reportes.Reporte_mas_vendidos reporte_mas_vendidos = new Reporte_mas_vendidos();
   Reportes.Reportes_Stock_Bajo stock_Bajo = new  Reportes_Stock_Bajo();
   Reportes.Reporte_producto_baja_rotacion reporte_producto_baja_rotacion = new Reporte_producto_baja_rotacion();
   Reportes.Reporte_entrada_Inventario reporte_entrada_Inventario = new Reporte_entrada_Inventario();
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonCerraSeccion;
    public static javax.swing.JMenuBar JMenu;
    public static javax.swing.JMenu JMenu_Iniciar_Almacen;
    public static javax.swing.JMenuItem JmenuLibroMayor;
    public static javax.swing.JMenuItem Jmenu_Abri_Empleado;
    public static javax.swing.JMenuItem Jmenu_abrir_Proveedor;
    public static javax.swing.JMenuItem MenuCategoria;
    public static javax.swing.JMenuItem MenuMarca;
    public static javax.swing.JMenuItem Menu_Ajustes_Inventario;
    public static javax.swing.JMenu Menu_Inicial_Empleado;
    public static javax.swing.JMenu Menu_Inicial_Producto;
    public static javax.swing.JMenuItem Menu_Inventario_Bajo_Reporte;
    public static javax.swing.JMenuItem Menu_Productos_bajarotacion;
    public static javax.swing.JMenuItem Menu_Reporte_Ganancias;
    public static javax.swing.JMenuItem Menu_Reporte_Margen_Ganancias;
    public static javax.swing.JMenuItem Menu_Reporte_Proveedores;
    public static javax.swing.JMenuItem Menu_Reportes_Entradas_Inventario;
    public static javax.swing.JMenuItem Menu_Reportes_Productos_Vendidos;
    public static javax.swing.JMenu Menu_Reportes_Sistema;
    public static javax.swing.JMenuItem Menu_Salidas_Inventario_Reporte;
    public static javax.swing.JMenuItem Menu_cotizacion;
    public static javax.swing.JMenu Menu_inicial_proveedor;
    public javax.swing.JButton btbGestionarAlmacen;
    public static javax.swing.JButton btbGestionarLibroContable;
    public javax.swing.JButton btbGestionarReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JMenuItem jMenuAbrirAlmacen;
    public static javax.swing.JMenuItem jMenuIInventarioUnidad;
    public static javax.swing.JMenuItem jMenuISALIDA_SOLIDO;
    public static javax.swing.JMenuItem jMenuInventarioLiquido;
    public static javax.swing.JMenuItem jMenuItemAjusteLiquiod;
    public static javax.swing.JMenuItem jMenuItemAjusteSolido;
    public static javax.swing.JMenuItem jMenuItemAjusteUnidad;
    public static javax.swing.JMenuItem jMenuItemCuentasContables;
    public static javax.swing.JMenuItem jMenuItemInventarioSolido;
    public static javax.swing.JMenuItem jMenuItemLiquidoSalida;
    public static javax.swing.JMenuItem jMenuItemUnidaSalida;
    public static javax.swing.JMenuItem jMenuIuSUARIOS;
    public static javax.swing.JMenu jMenuLibroContable;
    public static javax.swing.JMenuItem jMenuLibroDIARIO;
    public static javax.swing.JMenuItem jMenuProductoLiquido;
    public static javax.swing.JMenuItem jMenuProductoSolido;
    public static javax.swing.JMenuItem jMenuRegistrarUnidad;
    public static javax.swing.JMenu jMenu_Inventario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblUsuarioENLinea;
    // End of variables declaration//GEN-END:variables
}
