/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Usuari_Empleado;

import ModeloDAO.UsurioDAO;
import Validacion.Validar_contrasena;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adrian
 */
public class RecuperarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContrasena
     */
    public RecuperarContrasena() {
        initComponents();
        setTitle("Recuperar Contraseña");
        setLocationRelativeTo(null);
       this.setExtendedState(RecuperarContrasena.MAXIMIZED_BOTH);
       lblNuevaContrasena.setVisible(false);
       txtNuevaContrase.setVisible(false);
       lblConfirmaContrasena.setVisible(false);
       txtConfirmarContrsena.setVisible(false);
       btbActualizarContrsena.setVisible(false);
        lblCodigoDeVerificacion.setVisible(false);
        txtCodigoDeVerificacion.setVisible(false);
        btbConfirmar.setVisible(false);
        Contra.IniciarValidacionContrasena();
        Contra.IniciarValidacion();
        Contra.InicializarVerificacionCodigo();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreoRecuperar = new javax.swing.JTextField();
        txtNombreUsuarioRecuperar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btbVerificar = new javax.swing.JButton();
        lblNuevaContrasena = new javax.swing.JLabel();
        txtNuevaContrase = new javax.swing.JTextField();
        lblConfirmaContrasena = new javax.swing.JLabel();
        txtConfirmarContrsena = new javax.swing.JPasswordField();
        btbActualizarContrsena = new javax.swing.JButton();
        lblCodigoDeVerificacion = new javax.swing.JLabel();
        txtCodigoDeVerificacion = new javax.swing.JTextField();
        btbConfirmar = new javax.swing.JButton();
        lblValidarCorreo = new javax.swing.JLabel();
        lblValidarNombre = new javax.swing.JLabel();
        lblVerificarCodigo = new javax.swing.JLabel();
        lblValidarContrasena = new javax.swing.JLabel();
        lblConfirmarContrasenaValidacion = new javax.swing.JLabel();
        FondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recuperar Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Atras.png"))); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, -1, -1));

        lblNombreUsuario.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre de usuario :");
        jPanel1.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo electrónico :");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        txtCorreoRecuperar.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtCorreoRecuperar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCorreoRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 320, 30));

        txtNombreUsuarioRecuperar.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtNombreUsuarioRecuperar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNombreUsuarioRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 300, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/candado.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        btbVerificar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acepatar.png"))); // NOI18N
        btbVerificar.setText(" Verificar");
        btbVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(btbVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 667, -1, 30));

        lblNuevaContrasena.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblNuevaContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevaContrasena.setText("Nueva Contraseña :");
        jPanel1.add(lblNuevaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, 30));

        txtNuevaContrase.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtNuevaContrase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNuevaContrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 300, 30));

        lblConfirmaContrasena.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblConfirmaContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmaContrasena.setText("Confirma Contraseña :");
        jPanel1.add(lblConfirmaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, 30));

        txtConfirmarContrsena.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtConfirmarContrsena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtConfirmarContrsena, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 260, 30));

        btbActualizarContrsena.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbActualizarContrsena.setText("Actualizar");
        btbActualizarContrsena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbActualizarContrsenaActionPerformed(evt);
            }
        });
        jPanel1.add(btbActualizarContrsena, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 140, 30));

        lblCodigoDeVerificacion.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblCodigoDeVerificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoDeVerificacion.setText("Código de verificación :");
        jPanel1.add(lblCodigoDeVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        txtCodigoDeVerificacion.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtCodigoDeVerificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoDeVerificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDeVerificacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoDeVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 290, 30));

        btbConfirmar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbConfirmar.setText("Confimar");
        btbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btbConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 140, 30));

        lblValidarCorreo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarCorreo.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 340, 20));

        lblValidarNombre.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarNombre.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 320, 20));

        lblVerificarCodigo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblVerificarCodigo.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblVerificarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 290, 20));

        lblValidarContrasena.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValidarContrasena.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 300, 20));

        lblConfirmarContrasenaValidacion.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblConfirmarContrasenaValidacion.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblConfirmarContrasenaValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 320, 20));

        FondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/FondoCompleto.png"))); // NOI18N
        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1380, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new  Login_Ingreso().setVisible(true);
this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVerificarActionPerformed
        try {
            Contra.EnviarCorreoVALIDACION();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecuperarContrasena.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbVerificarActionPerformed

    private void btbActualizarContrsenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbActualizarContrsenaActionPerformed
        try {
            Contra.NuevaContrasena(this);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecuperarContrasena.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btbActualizarContrsenaActionPerformed

    private void btbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConfirmarActionPerformed
Contra.Confirmar();       // TODO add your handling code here:
    }//GEN-LAST:event_btbConfirmarActionPerformed

    private void txtCodigoDeVerificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDeVerificacionActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDeVerificacionActionPerformed

    /**
     * @param args the command line arguments
     */
 ModeloDAO.UsurioDAO us = new UsurioDAO();
 Validacion.Validar_contrasena Contra = new Validar_contrasena();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPantalla;
    public static javax.swing.JButton btbActualizarContrsena;
    public static javax.swing.JButton btbConfirmar;
    public static javax.swing.JButton btbVerificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblCodigoDeVerificacion;
    public static javax.swing.JLabel lblConfirmaContrasena;
    public static javax.swing.JLabel lblConfirmarContrasenaValidacion;
    public static javax.swing.JLabel lblCorreo;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblNuevaContrasena;
    public static javax.swing.JLabel lblValidarContrasena;
    public static javax.swing.JLabel lblValidarCorreo;
    public static javax.swing.JLabel lblValidarNombre;
    public static javax.swing.JLabel lblVerificarCodigo;
    public static javax.swing.JTextField txtCodigoDeVerificacion;
    public static javax.swing.JPasswordField txtConfirmarContrsena;
    public static javax.swing.JTextField txtCorreoRecuperar;
    public static javax.swing.JTextField txtNombreUsuarioRecuperar;
    public static javax.swing.JTextField txtNuevaContrase;
    // End of variables declaration//GEN-END:variables
}
